Source/EasyNetQ.Scheduler.Mongo.Core/EasyNetQ.Scheduler.Mongo.Core.csproj
Source/EasyNetQ.Scheduler.Mongo.Core/Properties/AssemblyInfo.cs
Source/EasyNetQ.Scheduler.Mongo.Core/packages.config
Source/EasyNetQ.Scheduler.Mongo/EasyNetQ.Scheduler.Mongo.csproj
Source/EasyNetQ.Scheduler.Mongo/Properties/AssemblyInfo.cs

Hi Mike!
Here are small fixes in Mongo Scheduler.

Fix version in csprojs and update mongo driver

---

Source/EasyNetQ.Tests/Integration/PublishSubscribeTests.cs
Source/EasyNetQ/Consumer/ConsumerFactory.cs
Source/EasyNetQ/Consumer/ExclusiveConsumer.cs
Source/EasyNetQ/Consumer/IConsumerConfiguration.cs
Source/EasyNetQ/Consumer/InternalConsumer.cs
Source/EasyNetQ/Consumer/StartConsumingStatus.cs
Source/EasyNetQ/DefaultMessageSerializationStrategy.cs
Source/EasyNetQ/EasyNetQ.csproj
Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs
Source/EasyNetQ/RabbitBus.cs
Source/Version.cs

https://github.com/mikehadlow/EasyNetQ/issues/301

Exclusive consumer

---

Source/EasyNetQ/ConnectionString/IConnectionStringParser.cs

ConnectionStringParser now implements IConnectionStringParser

---

Package/EasyNetQ/EasyNetQ.nuspec
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/packages.config
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.Hosepipe/packages.config
Source/EasyNetQ.LogReader/EasyNetQ.LogReader.csproj
Source/EasyNetQ.LogReader/packages.config
Source/EasyNetQ.Tests.Performance.Consumer/EasyNetQ.Tests.Performance.Consumer.csproj
Source/EasyNetQ.Tests.Performance.Consumer/packages.config
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/packages.config
Source/EasyNetQ.Trace/EasyNetQ.Trace.csproj
Source/EasyNetQ.Trace/packages.config
Source/EasyNetQ/EasyNetQ.csproj
Source/EasyNetQ/packages.config
Source/Version.cs

Hi guys!
Here is an upgrade of client to the latest version.

Upgrade client to 3.4.3

---

Source/EasyNetQ/RabbitBus.cs
Source/Version.cs

Bug fix of Rpc

---

Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
Source/EasyNetQ/ConnectionConfiguration.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/Producer/PersistentChannel.cs
Source/Version.cs

Utc datetimes

---

Source/EasyNetQ/RabbitHutch.cs
Source/Version.cs

Hi guys!
Here is very small addition to RabbitHutch :smile:

Very small CreateBus addition

---

Source/EasyNetQ/ComponentRegistration.cs
Source/Version.cs

Logging disabled by default

---

Source/EasyNetQ/LinqExtensions.cs
Source/EasyNetQ/RabbitBus.cs
Source/Version.cs

Hi guys!
It's small change about using default linq method instead of hand written.

AtLeastOneWithDefault -> DefaultIfEmpty

---

Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/Scheduler.cs

Revert "Priority queue support"

---

Source/EasyNetQ/RabbitHutch.cs
Source/Version.cs

Hi guys!
It's very small addition: it creates overloads for RabbitHutch.CreateBus, which was lost during refactoring :smile:

CreateBus overloads

---

Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/Scheduling/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/Version.cs

These are the changes from #416. It ended up being easier to just copy paste them over instead of reverting the revert that was done by @mikehadlow (the PR got merged before the RMQ 3.5.x update).
Also did some more clean up and reordering.

Priority queue support reloaded

---

Source/EasyNetQ/AutoSubscribe/SubscriptionConfigurationAttribute.cs
Source/Version.cs

This is useful in scenarios where you customize subscription configuration

Allow SubscriptionConfiguration to be applied to a class

---

Build/EasyNetQ.proj
Package/EasyNetQ.Serilog/EasyNetQ.Serilog.nuspec
Source/EasyNetQ.Serilog/EasyNetQ.Serilog.csproj
Source/EasyNetQ.Serilog/Properties/AssemblyInfo.cs
Source/EasyNetQ.Serilog/SerilogLogger.cs
Source/EasyNetQ.Serilog/packages.config
Source/EasyNetQ.sln
Source/Version.cs
build.bat

Added initial serilog support
Branched from pull request (so please merge this first):
https://github.com/EasyNetQ/EasyNetQ/pull/496

Add serilog package

---

Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/Version.cs

@Pliner is this a useful addiction?
the idea started from this thread: https://groups.google.com/forum/#!topic/easynetq/Zfu7yVcthvM

add synchronous consume(byte[]) methods

---

README.md

Update readme to reflect correct required version of VS.

---

Source/EasyNetQ/Producer/Rpc.cs
Source/Version.cs
hall_of_fame.md

Fix #520 Rpc.Respond overload not marked as virtual

Fix #520 Marked Rpc.Respond overload as virtual

---

Package/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.nuspec
Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
Source/EasyNetQ.DI.StructureMap/packages.config
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.DI.Tests/packages.config
Source/Version.cs

Fixes #555
Regarding version bump does this qualify as a breaking change? since there are breaking changes when upgrading StructueMap 3 -> 4?

Fix issue 555

---

Source/EasyNetQ.Hosepipe/Usage.txt
Source/Version.cs

fix the usage description to describe the option `x` the get (noack)

---

Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
Source/EasyNetQ.Hosepipe.Tests/ProgramTests.cs
Source/EasyNetQ.Hosepipe.Tests/QueueInsertionTests.cs
Source/EasyNetQ.Hosepipe.Tests/QueueRetrievalTests.cs
Source/EasyNetQ.Hosepipe/ErrorRetry.cs
Source/EasyNetQ.Hosepipe/Program.cs
Source/EasyNetQ.Hosepipe/QueueInsertion.cs
Source/EasyNetQ.Hosepipe/QueueRetrieval.cs
Source/EasyNetQ.Tests/ConventionsTests.cs
Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
Source/EasyNetQ/ComponentRegistration.cs
Source/EasyNetQ/Consumer/Base64ErrorMessageSerializer.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/Consumer/DefaultErrorMessageSerializer.cs
Source/EasyNetQ/Consumer/IErrorMessageSerializer.cs
Source/EasyNetQ/EasyNetQ.projitems

Add support binary (error)messages to HosePipe. Fixed #561

---

Source/Version.cs

@micdenny, ok with you? here's a version bump for https://github.com/EasyNetQ/EasyNetQ/pull/573

bumped version.cs

---

Source/EasyNetQ NET45/EasyNetQ NET45.csproj

disabled warning missing xml comments

---

Package/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.nuspec
Package/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.nuspec
Package/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.nuspec
Package/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.nuspec
Package/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.nuspec
Package/EasyNetQ.Serilog/EasyNetQ.Serilog.nuspec
Package/EasyNetQ/EasyNetQ.nuspec
Source/EasyNetQ.Hosepipe/EasyNetQHosepipeException.cs
Source/EasyNetQ.Tests.Messages/Messages.cs
Source/EasyNetQ.Tests.Tasks/Tasks/TestSimpleService.cs
Source/EasyNetQ.Tests/Integration/ExceptionConditionsTests.cs
Source/EasyNetQ.Tests/Integration/RequestResponseTests.cs
Source/EasyNetQ.Tests/Integration/Scheduling/PartyInvitation.cs
Source/EasyNetQ/AutoSubscribe/AutoSubscriberConsumerAttribute.cs
Source/EasyNetQ/AutoSubscribe/AutoSubscriberConsumerInfo.cs
Source/EasyNetQ/AutoSubscribe/ForTopicAttribute.cs
Source/EasyNetQ/AutoSubscribe/SubscriptionConfigurationAttribute.cs
Source/EasyNetQ/BasicGetResult.cs
Source/EasyNetQ/DeliveryModeAttribute.cs
Source/EasyNetQ/EasyNetQException.cs
Source/EasyNetQ/Producer/PublishInterruptedException.cs
Source/EasyNetQ/Producer/PublishNackedException.cs
Source/EasyNetQ/QueueAttribute.cs
Source/EasyNetQ/SystemMessages/ScheduleMe.cs
Source/EasyNetQ/SystemMessages/UnscheduleMe.cs
Source/EasyNetQ/TimeoutSecondsAttribute.cs
Source/Version.cs

Removed Serializable attribute from messages and exceptions

---

Build/EasyNetQ.proj
Package/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.nuspec
Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
Source/EasyNetQ.DI.SimpleInjector/InjectionExtensions.cs
Source/EasyNetQ.DI.SimpleInjector/Properties/AssemblyInfo.cs
Source/EasyNetQ.DI.SimpleInjector/SimpleInjectorAdapter.cs
Source/EasyNetQ.DI.SimpleInjector/SimpleInjectorMessageDispatcher.cs
Source/EasyNetQ.DI.SimpleInjector/packages.config
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.DI.Tests/SimpleInjectorAdapterTests.cs
Source/EasyNetQ.DI.Tests/packages.config
Source/EasyNetQ.sln
Source/Version.cs
hall_of_fame.md

This adds SimpleInjector support to the project.
I based the implementation on other adapters and added a nuspec file, like in #544 
I hope I did everything correctly. Let me know what you think :)

add SimpleInjector support to the project

---

Source/EasyNetQ/Scheduling/BusExtensions.cs
Source/EasyNetQ/Scheduling/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/Scheduling/DelayedExchangeScheduler.cs
Source/EasyNetQ/Scheduling/ExternalScheduler.cs
Source/EasyNetQ/Scheduling/IScheduler.cs
Source/Version.cs

replaces PR https://github.com/EasyNetQ/EasyNetQ/pull/599

Phil newman future publish topic

---

Package/EasyNetQ/EasyNetQ.nuspec
Source/Version.cs

Set upper bound of supported rabbitmq client version

---

Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
Source/EasyNetQ/ComponentRegistration.cs
Source/EasyNetQ/EasyNetQ.projitems
Source/EasyNetQ/IPersistentConnectionFactory.cs
Source/EasyNetQ/PersistentConnectionFactory.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/Version.cs

Allow injection of custom implementation of IPersistentConnection

---

Source/EasyNetQ.Scheduler.Tests/ScheduleRepositoryTests.cs
Source/EasyNetQ.Scheduler/ScheduleRepository.cs
Source/EasyNetQ.Scheduler/SchedulerService.cs
Source/EasyNetQ.Scheduler/SchedulerServiceFactory.cs
Source/Version.cs

Hi, we're currently using 0.50.12 at 15below and have made some stability fixes to the Scheduler that you might like!

EasyNetQ.Scheduler stability fixes

---

Source/EasyNetQ/Consumer/HandlerRunner.cs
Source/Version.cs

…so we can override the behavior

made some methods protected/virtual in HandlerRunner

---

Build/EasyNetQ.proj
Build/UpdateGitVersion.ps1
Build/UploadTestresults.ps1
GitVersion.yml
Source/EasyNetQ.sln
appveyor.yml

Add ability to create packages out of feature/netcore branch

Create packages out of feature/netcore branch

---

Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/Topology/Binding.cs
Source/EasyNetQ/Topology/IBinding.cs

IAdvancedBus is missing a possibility to put there headers for an exchange. I'd like to set up an exchange with headers, so I added the missing parameters.

Add header support to advancedbus

---

Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing.cs
Source/EasyNetQ.Tests/xunit.runner.json

version to allow release packages to be generated

disable .net standard 1.5 support for ninject and downgrade to non-beta

---

Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/Integration/RpcTests.cs
Source/EasyNetQ/Producer/Rpc.cs

fixes #748 
@arrkaye can you test this changes and let me know if now works for your use-case?

Publish RPC failure even for class without parameterless constructor

---

hall_of_fame.md

For pull request: Added support for infinite timeout in PersistentChannel.cs (#253)

Added Thomas Mutton to the hall of fame

---

Source/EasyNetQ/MessageFactory.cs

Very small change to get rid of unnecessary closure.

Got rid of closure

---

Source/EasyNetQ.Hosepipe.Tests/QueueRetrievalTests.cs
Source/EasyNetQ/Consumer/InternalConsumer.cs

fix for Double BasicConsumer initialization on InternalConsumer StartConsuming method 
https://github.com/EasyNetQ/EasyNetQ/issues/769

fix for Double BasicConsumer initialization

---

Source/EasyNetQ.Tests/PersistentConnectionTests.cs

Made one failing test explicit as it seems to fail on AppVeyor

Made one failing test explicit as it seems to fail on AppVeyor

---

Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.Scheduler.Mongo.Core/EasyNetQ.Scheduler.Mongo.Core.csproj
Source/EasyNetQ.Scheduler.Mongo.Tests/EasyNetQ.Scheduler.Mongo.Tests.csproj
Source/EasyNetQ.Scheduler.Tests/EasyNetQ.Scheduler.Tests.csproj
Source/EasyNetQ.Tests.Common/EasyNetQ.Tests.Common.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Trace/EasyNetQ.Trace.csproj
Source/EasyNetQ/EasyNetQ.csproj
Source/build.props

1. Tests are retargeted to netcore2
2. Tests libraries are updated to latest versions
3. ~~Windsor and NInject are updated and targeted to netstandart15~~ EasyNetQ is retargeted to netstandart20

Fix tests running in rider on mac

---

Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
Source/EasyNetQ.DI.Microsoft/EasyNetQServiceCollectionExtensions.cs
Source/EasyNetQ.DI.Microsoft/ServiceCollectionAdapter.cs
Source/EasyNetQ.DI.Tests/ContainerAdapterTests.cs
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.sln

Basic implementation of Microsoft.Extensions.DependecyInjection adapter

---

Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
Source/EasyNetQ.Hosepipe.Tests/FileMessageWriterTests.cs
Source/EasyNetQ.Hosepipe.Tests/MessageReaderTests.cs
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.Hosepipe/FileMessageWriter.cs
Source/EasyNetQ.Hosepipe/MessageReader.cs
Source/EasyNetQ.Hosepipe/Program.cs
Source/EasyNetQ.Hosepipe/QueueParameters.cs

Also, hosepipe becomes executable again :wink:

Hosepipe:  Create :o directory if it doesn't exist

---

Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.LogReader/EasyNetQ.LogReader.csproj
Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ/EasyNetQ.csproj

https://github.com/rabbitmq/rabbitmq-dotnet-client/releases/tag/v5.1.0

RabbitMQ .NET client 5.1.0

---

Source/EasyNetQ.Tests/ConsumeTests/AckStrategyTests.cs
Source/EasyNetQ/Consumer/AckStrategies.cs
Source/EasyNetQ/Consumer/InternalConsumer.cs
Source/EasyNetQ/Events/AckEvent.cs

I hope this strategy is not necessary anymore. Usages of it were removed in #803.

Remove AckStrategy.Nothing

---

Source/EasyNetQ.Tests/PersistentConnectionTests.cs
Source/EasyNetQ/Consumer/IConsumerFactory.cs
Source/EasyNetQ/Extensions.cs
Source/EasyNetQ/Producer/PersistentChannel.cs
Source/EasyNetQ/TimeBudget.cs

Limit retryTimeoutMs to MaxRetryTimeoutMs

---

Source/EasyNetQ/BasicGetResult.cs
Source/EasyNetQ/Consumer/HandlerCollection.cs
Source/EasyNetQ/Consumer/IHandlerRegistration.cs
Source/EasyNetQ/Consumer/IReceiveRegistration.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/IBus.cs
Source/EasyNetQ/ISerializer.cs
Source/EasyNetQ/JsonSerializer.cs
Source/EasyNetQ/Producer/IRpc.cs
Source/EasyNetQ/Producer/ISendReceive.cs
Source/EasyNetQ/Producer/Rpc.cs
Source/EasyNetQ/Producer/SendReceive.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/RabbitBus.cs

@zidad @khellang 
It seems https://github.com/EasyNetQ/EasyNetQ/pull/850 is not enough. We need to remove class constraint from all our API.

Remove class constraint

---

Source/EasyNetQ/Internals/Timers.cs

It's a defensive `try-catch` because not all exceptions are caught by callers of these helpers.

Catch an exception from a timer's callback, because it can crash the entire application

---

Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
Source/EasyNetQ.Tests/ModelCleanupTests.cs
Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent.cs
Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent_but_an_exception_is_thrown_by_responder.cs
Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent_but_no_reply_is_received.cs
Source/EasyNetQ/EasyNetQException.cs
Source/EasyNetQ/Producer/DefaultRpc.cs
Source/EasyNetQ/Producer/IRpc.cs

Rewrite RPC with async API

---

Source/EasyNetQ/IBus.cs
Source/EasyNetQ/Producer/DefaultSendReceive.cs
Source/EasyNetQ/Scheduling/DeadLetterExchangeAndMessageTtlScheduler.cs

Rewrite SendReceive with async API

---

Source/EasyNetQ/Consumer/ConsumerFactory.cs
Source/EasyNetQ/Consumer/ExclusiveConsumer.cs
Source/EasyNetQ/Consumer/PersistentConsumer.cs
Source/EasyNetQ/Consumer/PersistentMultipleConsumer.cs
Source/EasyNetQ/Internals/ConcurrentSet.cs

@zidad @micdenny Hope you will not against these changes

Simplify usage of ConcurrentDictionary

---

Source/EasyNetQ/Internals/AwaitableDisposable.cs

added comments on AwaitableDisposable to clear out the purpose of that structure

added comments on AwaitableDisposable

---

Source/EasyNetQ.Scheduler.Mongo.Tests/SchedulerServiceTests.cs
Source/EasyNetQ.Scheduler.Mongo/ConfigurationBase.cs
Source/EasyNetQ.Scheduler.Mongo/SchedulerServiceConfiguration.cs
Source/EasyNetQ.Scheduler.Mongo/SchedulerServiceFactory.cs
Source/EasyNetQ.Scheduler.Mongo/app.config
Source/EasyNetQ.Scheduler.Tests/SchedulerServiceTests.cs
Source/EasyNetQ.Scheduler/ConfigurationBase.cs
Source/EasyNetQ.Scheduler/SchedulerServiceConfiguration.cs
Source/EasyNetQ.Scheduler/SchedulerServiceFactory.cs
Source/EasyNetQ.Scheduler/app.config

Update EasyNetQ.Scheduler to include config setting to be able to invoke legacy conventions on creation of rabbit bus

Update EasyNetQ.Scheduler with EnableLegacyConventions setting

---

Source/EasyNetQ/Internals/AsyncCache.cs
Source/EasyNetQ/MessageVersioning/VersionedPublishExchangeDeclareStrategy.cs
Source/EasyNetQ/MultipleExchange/MultipleExchangePublishExchangeDeclareStrategy.cs
Source/EasyNetQ/Producer/PublishExchangeDeclareStrategy.cs

PR removes the boilerplate code in caching declared exchanges

Move caching of declared exchanges to AsyncCache

---

Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
Source/EasyNetQ.Tests/MessageVersioningTests/VersionedPublishExchangeDeclareStrategyTests.cs
Source/EasyNetQ.Tests/MultipleExchangeTest/MultipleExchangePublishExchangeDeclareStrategyTests.cs
Source/EasyNetQ.Tests/ProducerTests/PublishExchangeDeclareStrategyTests.cs
Source/EasyNetQ/AdvancedBusExtensions.cs
Source/EasyNetQ/DelayedExchangeExtensions.cs
Source/EasyNetQ/ExchangeDeclareConfiguration.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/QueueDeclareConfiguration.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/Scheduling/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/Scheduling/DelayedExchangeScheduler.cs
Source/EasyNetQ/Scheduling/ExternalScheduler.cs

PR is the same as  #921 but for exchanges.

Rework exchange declaration

---

Source/EasyNetQ.Tests/AmqpExceptionParserTests.cs
Source/EasyNetQ.Tests/ConnectionString/ConnectionStringGrammarTests.cs
Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
Source/EasyNetQ/AmqpExceptions/AmpqExceptionGrammar.cs
Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
Source/EasyNetQ/ConnectionString/IConnectionStringParser.cs
Source/EasyNetQ/Producer/PersistentChannel.cs
Source/EasyNetQ/Properties/AssemblyInfo.cs
Source/EasyNetQ/Sprache/Failure.cs
Source/EasyNetQ/Sprache/IFailure.cs
Source/EasyNetQ/Sprache/IResultOfT.cs
Source/EasyNetQ/Sprache/ISuccess.cs
Source/EasyNetQ/Sprache/Input.cs
Source/EasyNetQ/Sprache/Parse.cs
Source/EasyNetQ/Sprache/ParseException.cs
Source/EasyNetQ/Sprache/ParserOfT.cs
Source/EasyNetQ/Sprache/ResultHelper.cs
Source/EasyNetQ/Sprache/Success.cs

Move code from Sprache to EasyNetQ.Sprache namespace and internalise it.

---

Source/EasyNetQ.Hosepipe/FileMessageWriter.cs
Source/EasyNetQ.Hosepipe/Usage.txt
Source/EasyNetQ.Tests.Tasks/Tasks/SimpleRequester/LatencyRecorder.cs
Source/EasyNetQ.Tests.Tasks/Tasks/TestSimpleService.cs
Source/EasyNetQ.Tests/MessageVersioningTests/VersionedPublishExchangeDeclareStrategyTests.cs
Source/EasyNetQ/AdvancedBusExtensions.cs

Spell check

---

Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs

Make HandleConsumerCancelled virtual

---

Source/EasyNetQ.Tests/SerializationTests.cs
Source/EasyNetQ/EasyNetQException.cs

Fixes #705
https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netstandard-2.0

Make EasyNetQ exceptions really serializable

---

Source/EasyNetQ/EasyNetQ.csproj
Source/EasyNetQ/LightInject/LightInject.cs
Source/EasyNetQ/Producer/ClientCommandDispatcherSingleton.cs

https://github.com/EasyNetQ/EasyNetQ/issues/623

Additional .NET 4.6 target for dispatcher deadlock

---

Source/EasyNetQ/Producer/Rpc.cs

Dispose consumer cancellation for RPC response queue 

---

Source/EasyNetQ.Tests/FluentConfiguration/SubscriptionConfigurationTests.cs
Source/EasyNetQ.Tests/Integration/SubscribeWithQueueModeTests.cs
Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs
Source/EasyNetQ/Producer/DefaultPubSub.cs

Addresses #927 . 
A lot of this is based on guess work so please feel free to point out if this is completely in the wrong direction. Thanks.

Add option to subscribe to lazy queues.

---

Source/EasyNetQ.Tests/ConsumeTests/DefaultConsumerErrorStrategyTests.cs
Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs

https://github.com/EasyNetQ/EasyNetQ/issues/994 Added publisher confirms to DefaultConsumerErrorStrategy.
Let me know what you think. I hope it will be fixed 🍡

Added unit tests and publisher confirm to DefaultConsumerErrorStrategy

---

Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
Source/EasyNetQ/EasyNetQ.csproj
appveyor.yml

Add SourceLink support

---

appveyor.yml

Do not skip symbols

---

Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ/EasyNetQ.csproj

Bump Newtonsoft.Json to 12.0.3

---

RabbitMQ/Dockerfile
Source/EasyNetQ/Scheduling/DelayedExchangeScheduler.cs
docker-compose.yaml

Fixes #976
Before such queue was created:

Fix of DelayedExchangeScheduler: do not create extra queue

---

README.md

Add new badges, change png to svg

---

CODEOWNERS
appveyor.yml

It will help to setup branch protection rules

Add CODEOWNERS

---

Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
Source/EasyNetQ/EasyNetQ.csproj

For IntelliSense experience, 598 KB with docs vs 531 KB without docs.

Add xml docs in package

---

Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj

Up to date version of the client fixes several integration tests.

Bump management client

---

Source/EasyNetQ/Producer/DefaultRpc.cs

This issue was found by integration tests

Fix RPC when using legacy conventions

---

Source/EasyNetQ.Tests/Mocking/MockBuilder.cs
Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent_but_the_connection_closes_before_a_reply_is_received.cs
Source/EasyNetQ/PersistentConnection.cs

Connection implements IAutorecoveringConnection instead of IRecovery

---

Source/EasyNetQ.Tests/FluentConfiguration/PublishConfigurationTests.cs
Source/EasyNetQ/FluentConfiguration/IPublishConfiguration.cs
Source/EasyNetQ/FluentConfiguration/IRequestConfiguration.cs
Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs

Do not allow to pass null topic to IPublishConfiguration

---

Source/EasyNetQ/Preconditions.cs

- eliminate string.Format() allocations
- fix xml comments
- add generic constraints
- add nameof
This allows us to get rid of a lot of unnecessary memory allocations - every command dispatch, publish message, exchange declaration, bind...

Refactor preconditions

---

.editorconfig
Source/EasyNetQ.sln
Source/build.props
Source/build.targets

I suggest expanding editorconfig rules file. In principle, these are the rules that the vast majority of repositories I've seen adhere to.

Add more editorconfig rules, add solution items

---

Source/EasyNetQ/FluentConfiguration/IPublishConfiguration.cs

Remove PublishConfiguration.QueueName

---

Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
Source/EasyNetQ/ConnectionConfiguration.cs
Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
Source/EasyNetQ/Consumer/ConsumerDispatcher.cs
Source/EasyNetQ/DI/ConnectionFactoryFactory.cs

Delete this option and convert the remain threads to the background. 
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/846

Drop UseBackgroundThreads

---

Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ/EasyNetQ.csproj
appveyor.yml

Also, this PR fixes build because of the recent update of appveyor image.

Bump rabbitmq client

---

Source/EasyNetQ.Tests/ProducerTests/When_a_message_is_sent.cs
Source/EasyNetQ/Consumer/IConsumerConfiguration.cs
Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/DefaultMessageSerializationStrategy.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/DefaultSendReceive.cs
Source/EasyNetQ/DelayedExchangeScheduler.cs
Source/EasyNetQ/ExternalScheduler.cs
Source/EasyNetQ/FuturePublishConfiguration.cs
Source/EasyNetQ/IMessageSerializationStrategy.cs
Source/EasyNetQ/IScheduler.cs
Source/EasyNetQ/ISendReceive.cs
Source/EasyNetQ/RequestConfiguration.cs
Source/EasyNetQ/ResponderConfiguration.cs
Source/EasyNetQ/SchedulerExtensions.cs
Source/EasyNetQ/SendConfiguration.cs
Source/EasyNetQ/SendReceiveExtensions.cs
Source/EasyNetQ/SubscriptionConfiguration.cs

Fixes #945.
Related to #956, #981

Priority support

---

Build/EasyNetQ.proj
Source/EasyNetQ/Consumer/ConsumerDispatcher.cs

Fix Argument exception is thrown on dispose of consumer dispatcher

---

Source/EasyNetQ/Consumer/ConsumerDispatcher.cs
Source/EasyNetQ/Producer/ClientCommandDispatcherSingleton.cs

The same fix https://github.com/EasyNetQ/EasyNetQ/pull/1096, but for ClientCommandDispatcher

Fix Argument exception is thrown on dispose of client dispatcher

---

Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Scheduler.Mongo.Tests/EasyNetQ.Scheduler.Mongo.Tests.csproj
Source/EasyNetQ.Scheduler.Tests/EasyNetQ.Scheduler.Tests.csproj
Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ/EasyNetQ.csproj

Bump RabbitMQ.Client to 6.2.1

---

Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
Source/EasyNetQ.Hosepipe.Tests/ProgramTests.cs
Source/EasyNetQ.Hosepipe.Tests/QueueRetrievalTests.cs
Source/EasyNetQ.Hosepipe.Tests/TestExtensions.cs
Source/EasyNetQ.Hosepipe.Tests/xunit.runner.json
Source/EasyNetQ.Hosepipe/ErrorRetry.cs
Source/EasyNetQ.Hosepipe/FileMessageWriter.cs
Source/EasyNetQ.Hosepipe/IQueueInsertion.cs
Source/EasyNetQ.Hosepipe/Program.cs
Source/EasyNetQ.Hosepipe/QueueInsertion.cs
Source/EasyNetQ.Hosepipe/QueueRetrieval.cs

Hosepipe. Insert messages to a queue instead of an exchange

---

Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
Source/EasyNetQ.Hosepipe.Tests/MessageReaderTests.cs
Source/EasyNetQ.Hosepipe/Program.cs
Source/EasyNetQ.Tests/ConventionsTests.cs
Source/EasyNetQ.Tests/Interception/BuildInInterceptorsTests.cs
Source/EasyNetQ/DefaultTypeNameSerializer.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/ITypeNameSerializer.cs
Source/EasyNetQ/LegacyTypeNameSerializer.cs
Source/EasyNetQ/MessageProperties.cs
Source/EasyNetQ/MessageReceivedInfo.cs
Source/EasyNetQ/PullingConsumer.cs
Source/EasyNetQ/PullingConsumerExtensions.cs
Source/EasyNetQ/PullingConsumerFactory.cs
Source/EasyNetQ/RabbitAdvancedBus.cs

1. Fix typos #1073
1. MessageReceivedInfo is read-only, also xml docs are added
1. Fix review comments from #1073
1. Xml docs for TypeNameSerializers

Various fixes

---

Source/EasyNetQ.Hosepipe.Tests/ArgParserTests.cs
Source/EasyNetQ.Hosepipe.Tests/ErrorMessageRepublishSpike.cs
Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
Source/EasyNetQ.Hosepipe.Tests/Helper.cs
Source/EasyNetQ.Hosepipe.Tests/MessageReaderTests.cs
Source/EasyNetQ.Hosepipe.Tests/ProgramTests.cs
Source/EasyNetQ.Hosepipe.Tests/QueueInsertionTests.cs
Source/EasyNetQ.Hosepipe.Tests/QueueRetrievalTests.cs
Source/EasyNetQ.Hosepipe.Tests/TestExtensions.cs
Source/EasyNetQ.Hosepipe/ErrorRetry.cs
Source/EasyNetQ.Hosepipe/HosepipeConnection.cs
Source/EasyNetQ.Hosepipe/HosepipeMessage.cs
Source/EasyNetQ.Hosepipe/Program.cs
Source/EasyNetQ.Hosepipe/QueueInsertion.cs
Source/EasyNetQ.Hosepipe/QueueParameters.cs
Source/EasyNetQ.Hosepipe/QueueRetrieval.cs

Enable publish confirms, improve connection management

---

Source/EasyNetQ.Tests.Tasks/Tasks/TestSimpleService.cs
Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
Source/EasyNetQ.Tests/MessageVersioningTests/VersionedExchangeDeclareStrategyTests.cs
Source/EasyNetQ.Tests/MultipleExchangeTest/MultipleExchangeExchangeDeclareStrategyTests.cs
Source/EasyNetQ/ConnectionConfigurationExtensions.cs
Source/EasyNetQ/Conventions.cs
Source/EasyNetQ/DefaultRpc.cs

Parameterize RpcReturnQueueNamingConvention by response type

---

Source/EasyNetQ.IntegrationTests/Advanced/When_declare_a_queue.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_declare_an_exchange_with_different_properties.cs
Source/EasyNetQ/QueueDeclareConfigurationExtensions.cs
Source/EasyNetQ/QueueMode.cs
Source/EasyNetQ/QueueType.cs

Add basic quorum queue support

---

Source/EasyNetQ/RabbitAdvancedBus.cs

Fix logging: arguments could be null

---

Source/EasyNetQ.Tests/NonGenericPubSubExtensionsTests.cs
Source/EasyNetQ.Tests/NonGenericRpcExtensionsTests.cs
Source/EasyNetQ.Tests/NonGenericSchedulerExtensionsTests.cs
Source/EasyNetQ.Tests/NonGenericSendExtensionsTests.cs
Source/EasyNetQ/NonGenericPubSubExtensions.cs
Source/EasyNetQ/NonGenericRpcExtensions.cs
Source/EasyNetQ/NonGenericSchedulerExtensions.cs
Source/EasyNetQ/NonGenericSendReceiveExtensions.cs

Fixes #558, #833, #1145
If anyone knows a better approach to create delegates(to call generic method from non-generic) feel free to share 😉

Non-generic FuturePublish, Publish, Send, Request

---

Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
Source/EasyNetQ/ConnectionConfiguration.cs
Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/DefaultSendReceive.cs
Source/EasyNetQ/DelayedExchangeScheduler.cs
Source/EasyNetQ/NonGenericPubSubExtensions.cs
Source/EasyNetQ/NonGenericRpcExtensions.cs
Source/EasyNetQ/NonGenericSchedulerExtensions.cs
Source/EasyNetQ/NonGenericSendReceiveExtensions.cs

Helps a bit to mitigate the issue #1149

Allow to publish with mandatory flag

---

.github/workflows/ci.yml
Build/EasyNetQ.proj
Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
Source/EasyNetQ.DI.Tests/ContainerAdapterTests.cs
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.DI.Tests/MicrosoftDependencyScopeTests.cs
Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Tests/DefaultTypeNameSerializerTests.cs
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/LegacyTypeNameSerializerTests.cs
Source/EasyNetQ/ConnectionConfigurationExtensions.cs
Source/EasyNetQ/ConnectionString/AmqpConnectionStringParser.cs
Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
Source/EasyNetQ/DefaultTypeNameSerializer.cs
Source/EasyNetQ/EasyNetQ.csproj
Source/EasyNetQ/RabbitHutch.cs

It seems to be ok to drop net461 starting from v7.

Drop net461 support

---

Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

Drop legacy setDeadLetterRoutingKey

---

.github/workflows/ci.yml
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Tests/DefaultTypeNameSerializerTests.cs
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/LegacyTypeNameSerializerTests.cs

Test on dotnet core 5

---

Source/EasyNetQ/DefaultSendReceive.cs
Source/EasyNetQ/ReceiveConfiguration.cs

It allows to configure a queue on SingleActiveConsumer mode using Receive configuration

Add SingleActiveConsumer to receive configuration

---

Source/EasyNetQ.Tests/FluentConfiguration/SubscriptionConfigurationTests.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/SubscriptionConfiguration.cs

Added WithQueueType to SubscriptionConfiguration

---

Source/EasyNetQ.Approval.Tests/ApprovalTests.cs
Source/EasyNetQ.Approval.Tests/EasyNetQ.Approval.Tests.csproj
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.Autofac.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.LightInject.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.Microsoft.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.Ninject.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.SimpleInjector.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.StructureMap.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.DI.Windsor.approved.txt
Source/EasyNetQ.Approval.Tests/EasyNetQ.approved.txt
Source/EasyNetQ.sln
Source/Tests.props

It helps to see changes in public API.

Approval tests

---

Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_inflight_during_shutdown.cs

Test for the behaviour of responder cancellation

---

Source/EasyNetQ/Consumer/InternalConsumer.cs

Fixes #1232
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1082

Stop consumers with BasicCancelNoWait

---

Source/EasyNetQ.DI.Autofac/AutofacAdapter.cs
Source/EasyNetQ.DI.LightInject/LightInjectAdapter.cs
Source/EasyNetQ.DI.Microsoft/ServiceCollectionAdapter.cs
Source/EasyNetQ.DI.Ninject/NinjectAdapter.cs
Source/EasyNetQ.DI.SimpleInjector/SimpleInjectorAdapter.cs
Source/EasyNetQ.DI.StructureMap/StructureMapAdapter.cs
Source/EasyNetQ.DI.Windsor/WindsorAdapter.cs
Source/EasyNetQ/DI/DefaultServiceContainer.cs

To reduce amount of build warnings

Add missing xml docs to DI adapters

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.DI.Microsoft/ServiceCollectionAdapter.cs
Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
Source/EasyNetQ/DI/IConsumeScopeProvider.cs
Source/EasyNetQ/NonGenericSendReceiveExtensions.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

This PR implements @Pliner suggestion from #1277 : https://github.com/EasyNetQ/EasyNetQ/pull/1277#issuecomment-926364129

Add IConsumeScopeProvider

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/NonGenericPubSubExtensionsTests.cs
Source/EasyNetQ/NonGenericPubSubExtensions.cs
Source/EasyNetQ/PubSubExtensions.cs

Fixed #1218
This implementation is merely the same as it is done for Publish stuff.

NonGeneric subscribe implementation

---

Source/EasyNetQ.ApprovalTests/ApprovalTests.cs
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Hosepipe.Tests/ProgramIntegrationTests.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_consumer_with_auto_ack.cs
Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_queue_type.cs
Source/EasyNetQ.Tests/ConsumeTests/ConsumerTestBase.cs
Source/EasyNetQ.Tests/ConsumeTests/When_consume_is_called_with_auto_ack.cs
Source/EasyNetQ.Tests/PersistentConsumerTests/Given_a_PersistentConsumer.cs
Source/EasyNetQ/AdvancedBusExtensions.cs
Source/EasyNetQ/ConsumeConfiguration.cs
Source/EasyNetQ/Consumer/AsyncBasicConsumer.cs
Source/EasyNetQ/Consumer/Consumer.cs
Source/EasyNetQ/Consumer/ConsumerFactory.cs
Source/EasyNetQ/Consumer/HandlerRunner.cs
Source/EasyNetQ/Consumer/IConsumerErrorStrategy.cs
Source/EasyNetQ/Consumer/InternalConsumer.cs
Source/EasyNetQ/Consumer/InternalConsumerFactory.cs
Source/EasyNetQ/Events/ConnectionRecoveredEvent.cs
Source/EasyNetQ/IEventBus.cs
Source/EasyNetQ/MessageVersioning/MessageTypeProperty.cs
Source/EasyNetQ/Preconditions.cs
Source/EasyNetQ/RabbitAdvancedBus.cs

Fixes #1290
A couple of things about the implementation:
1. Supported only in advanced API.
2. AckEvent is not raised if autoack is enabled as well as ackstrategy is not called.

Support auto-ack

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs

Simplify Connect/IsConnected

---

.github/workflows/ci.yml
Source/EasyNetQ.ApprovalTests/EasyNetQ.ApprovalTests.csproj
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Serialization.Tests/EasyNetQ.Serialization.Tests.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/LegacyTypeNameSerializerTests.cs
Source/NuGet.Config

Bump to net6

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Hosepipe/QueueRetrieval.cs
Source/EasyNetQ.Serialization.Tests/SerializerTests.cs
Source/EasyNetQ.Tests/MessagePropertiesTests.cs
Source/EasyNetQ/Consumer/AsyncBasicConsumer.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/MessageProperties.cs
Source/EasyNetQ/MessagePropertiesExtensions.cs
Source/EasyNetQ/Persistent/PersistentChannel.cs
Source/EasyNetQ/Producer/MessagePropertiesExtensions.cs
Source/EasyNetQ/Properties/AssemblyInfo.cs
Source/EasyNetQ/PublishConfiguration.cs
Source/EasyNetQ/PullingConsumer.cs

Message expires should be TimeSpan

---

.github/workflows/ci.yml

Since NET6 dotnet format is a built-in SDK tool.

Use built-in dotnet format tool

---

Source/EasyNetQ/ConnectionConfiguration.cs
Source/EasyNetQ/ConnectionConfigurationExtensions.cs

Refactor client properties: extend platform, add os, remove net_version

---

Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ/EasyNetQ.csproj
Source/NuGet.Config

https://github.com/rabbitmq/rabbitmq-dotnet-client/releases/tag/v6.3.0

Support RabbitMQ.Client 6.3+

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.ApprovalTests.csproj
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt

Bump PublicApiGenerator

---

Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj

Bump integration tests deps

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.ApprovalTests.csproj
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
Source/EasyNetQ.Serialization.Tests/EasyNetQ.Serialization.Tests.csproj
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj

Fix of "no tests found" in CI

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.DI.Windsor.approved.txt
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.DI.Windsor/RemovableNamingSubSystem.cs
Source/EasyNetQ.DI.Windsor/WindsorContainerExtensions.cs
Source/EasyNetQ.Examples.DlxRetry/EntryPoint.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

Extensions for SimpleConsumerErrorStrategy

---

Source/EasyNetQ/DI/ConnectionFactoryFactory.cs

Initialize ConnectionFactory.HostName

---

Source/EasyNetQ.Examples.DlxRetry/EasyNetQ.Examples.DlxRetry.csproj
Source/EasyNetQ.Examples.DlxRetry/EntryPoint.cs

Example cleanup

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
Source/EasyNetQ/Interception/CompositeProduceConsumerInterceptor.cs
Source/EasyNetQ/Interception/NoopProduceConsumeInterceptor.cs
Source/EasyNetQ/Interception/ProduceConsumerInterceptorExtensions.cs
Source/EasyNetQ/PullingConsumer.cs
Source/EasyNetQ/PullingConsumerFactory.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

Inject IEnumerable of interceptors

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/AdvancedBusExtensions.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/RabbitAdvancedBus.cs

The same, but for Unbind.
https://github.com/EasyNetQ/EasyNetQ/commit/c722a0e9951ad524436c07906ea377cfa315a123

Allow to unbind without Binding<T>

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.IntegrationTests/Advanced/When_moving_messages.cs
Source/EasyNetQ/MoveMessagesExtensions.cs

Shortcut to move messages between queues

---

.github/workflows/ci.yml

https://github.com/PublicApiGenerator/PublicApiGenerator/pull/247

Use fixed dotnet version

---

.github/workflows/ci.yml

To fix the deprecation warning.

Switch to latest ubuntu

---

Source/EasyNetQ/Sprache/Failure.cs
Source/EasyNetQ/Sprache/Input.cs
Source/EasyNetQ/Sprache/Parse.cs
Source/EasyNetQ/Sprache/ParseException.cs
Source/EasyNetQ/Sprache/ParserOfT.cs
Source/EasyNetQ/Sprache/ResultHelper.cs
Source/EasyNetQ/Sprache/Success.cs

The parsing code is pretty stable and it is unlikely that advanced Sprache parsers will ever be needed.

Remove unused Sprache code

---

Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_performed_on_a_broken_channel.cs
Source/EasyNetQ/Persistent/PersistentChannel.cs

Retry BrokerUnreachableException

---

Source/Directory.Build.props

Stop using PublicSign

---

Source/EasyNetQ.Logging.Microsoft/EasyNetQ.Logging.Microsoft.csproj
Source/EasyNetQ.Logging.Serilog/EasyNetQ.Logging.Serilog.csproj

Add descriptions for logging packages

---

Source/EasyNetQ.IntegrationTests/RabbitMQFixture.cs

Switch to the latest rabbitmq in tests

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/ConnectionConfiguration.cs
Source/EasyNetQ/DI/ConnectionFactoryFactory.cs

Somehow addresses #1467, #1456.

Allow to specify ConsumerDispatcherConcurrency

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.DI.Autofac/AutofacAdapter.cs
Source/EasyNetQ.Serialization.NewtonsoftJson/NewtonsoftJsonSerializer.cs
Source/EasyNetQ/AutoSubscribe/AutoSubscriber.cs
Source/EasyNetQ/ChannelDispatcher/PersistentChannelDispatchOptions.cs
Source/EasyNetQ/ConnectionConfigurationExtensions.cs
Source/EasyNetQ/ConnectionString/AmqpConnectionStringParser.cs
Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
Source/EasyNetQ/Consumer/Consumer.cs
Source/EasyNetQ/Internals/AsyncCache.cs
Source/EasyNetQ/Internals/ConcurrentDictionaryExtensions.cs
Source/EasyNetQ/Internals/DisposableAction.cs
Source/EasyNetQ/Internals/ReadOnlyMemoryStream.cs
Source/EasyNetQ/Internals/TaskHelpers.cs
Source/EasyNetQ/JsonSerializer.cs
Source/EasyNetQ/MessageFactory.cs
Source/EasyNetQ/MessageProperties.cs
Source/EasyNetQ/Persistent/PersistentChannel.cs
Source/EasyNetQ/Persistent/PersistentConnection.cs
Source/EasyNetQ/Sprache/Input.cs
Source/EasyNetQ/Sprache/ParserOfT.cs

After #1475, there are more nullability warnings.

Fix nullability warnings

---

Source/Directory.Build.props

To prevent this kind of PRs #1477.

Suppress strong name error, treat warnings as errors

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/AdvancedBusExtensions.cs

Add missing Consume extensions overload

---

Source/EasyNetQ/DefaultMessageSerializationStrategy.cs

The creation of `ArrayPooledMemoryStream` was done in a hurry just to fix compilation with nullability feature.

Do not allocate ArrayPooledMemoryStream if body is null

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/FuturePublishConfiguration.cs
Source/EasyNetQ/Internals/DictionaryExtensions.cs
Source/EasyNetQ/MessageProperties.cs
Source/EasyNetQ/MessagePropertiesExtensions.cs
Source/EasyNetQ/PublishConfiguration.cs
Source/EasyNetQ/RequestConfiguration.cs
Source/EasyNetQ/SendConfiguration.cs

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/api/IBasicProperties.cs#L82

Headers should be IDictionary<string, object?>

---

Source/FodyWeavers.xml

AutoDetect doesn't work properly in our case.
```
Process terminated. Assertion failed.
[NullGuard] messageFunc is null.
at EasyNetQ.Logging.Serilog.SerilogLoggerAdapter.Log(LogLevel logLevel, Func`1 messageFunc, Exception exception, Object[] formatParameters) in /Users/yurypliner/Sources/EasyNetQ/Source/EasyNetQ.Logging.Serilog/SerilogLoggerAdapter.cs:line 24
at EasyNetQ.Logging.LoggerExtensions.IsInfoEnabled(ILogger logger) in /Users/yurypliner/Sources/EasyNetQ/Source/EasyNetQ/Logging/LoggerExtensions.cs:line 49
at EasyNetQ.Logging.LoggerExtensions.InfoFormat(ILogger logger, String message, Object[] args) in /Users/yurypliner/Sources/EasyNetQ/Source/EasyNetQ/Logging/LoggerExtensions.cs:line 338
at EasyNetQ.Persistent.PersistentConnection.InitializeConnection() in …
```

Switch NullGuard to NullableReferenceTypes mode

---

.github/workflows/ci.yml
.github/workflows/depsreview.yaml
Source/EasyNetQ.sln

Bump actions/checkout version

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/MessageFactoryTests.cs
Source/EasyNetQ/MessageFactory.cs

Ditch unused MessageFactory.CreateInstance overload

---

Source/EasyNetQ.sln
Source/docker-compose.yml

Add docker-compose file with rabbitmq cluster

---

Source/EasyNetQ.ApprovalTests/ApprovalTests.cs
Source/EasyNetQ.ApprovalTests/EasyNetQ.Logging.Microsoft.approved.txt
Source/EasyNetQ.ApprovalTests/EasyNetQ.Logging.Serilog.approved.txt
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Logging.Microsoft/MicrosoftLoggerAdapter.cs
Source/EasyNetQ.Logging.Serilog/SerilogLoggerAdapter.cs
Source/EasyNetQ/Logging/ConcurrentColoredConsole.cs
Source/EasyNetQ/Logging/ConsoleLogger.cs
Source/EasyNetQ/Logging/NoopLogger.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

These implementations are not used.

Ditch non generic logger implementations

---

Source/EasyNetQ.sln
Source/EasyNetQ/MessageFactory.cs
hall_of_fame.md

In new .NET versions, especially since NET 5.0 and newer, compiled lambda expressions are much faster than `Activator.CreateInstance` when creating new objects dynamically.
I'd like to share an implementation of MessageFactory that we're using. It is about 20 times faster than the current one.
When message count is in range of 10k/s just creating new message instances takes time in order of single milliseconds, which I find significant enough.
I didn't add any input parameter validation for performance reasons so it will throw in the same cases as existing implementation.
There already is a test checking that it is working correctly (`MessageFactoryTests.Should_correctly_create_generic_message`).
Quick benchmark for comparison: https://github.com/pziezio/EasyNetQ/commit/ceee32d8b449ae98b5d …

Optimize MessageFactory with compiled lambda expressions

---

Source/EasyNetQ/Logging/ConsoleLogger.cs

Add notes about ConsoleLogger

---

index.html

Fixes #1534 and updates the download counter.

Update to the latest

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/Conventions.cs

Fixes #1460
Of course, this is not ideal, but it allows at least to customize.

Allow to specify error queue type

---

Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs

Do not allocate dictionary

---

Source/EasyNetQ/Consumer/HandlerCollection.cs

Fix problem with parallel subscribe

Replace Dictionary with ConcurrentDictionary for HandlerCollection

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/MessagePropertiesExtensions.cs

Open extensions to copy MessageProperties to IBasicProperties and back

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_invoked.cs
Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_performed_on_a_broken_channel.cs
Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_performed_on_a_closed_channel_that_doesnt_open_again.cs
Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_performed_on_a_closed_channel_that_then_opens.cs
Source/EasyNetQ/Persistent/PersistentChannel.cs
Source/EasyNetQ/Persistent/PersistentChannelFactory.cs

Log exception if failed to invoke a channel action

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/Conventions.cs

Customise error exchange type

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/SendReceiveExtensions.cs

New ReceiveAsync overloads to mitigate #1560

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.DI.Microsoft/ServiceCollectionAdapter.cs
Source/EasyNetQ/DI/AsyncServiceResolverScope.cs
Source/EasyNetQ/DI/IConsumeScopeProvider.cs
Source/EasyNetQ/RabbitAdvancedBus.cs

https://andrewlock.net/exploring-dotnet-6-part-10-new-dependency-injection-features-in-dotnet-6/
Actually now MSDI is the only container that supports this.

Add support for IAsyncDisposable implementations without IDisposable

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.IntegrationTests/Advanced/When_declare_an_exchange_with_different_properties.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_publish_to_non_existent_exchange.cs
Source/EasyNetQ/ExchangeType.cs
Source/EasyNetQ/SubscriptionConfiguration.cs

Move of the other constants are there.

Move ExchangeType.cs to root namespace

---

Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_custom_prefetch_count.cs
Source/EasyNetQ/Internals/TaskHelpers.cs

Partially fixes #1576 only for sync callbacks.

Prevent sync callbacks to block consumer dispatcher

---

Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
Source/EasyNetQ.Tests/MessageVersioningTests/MessageTypePropertyTests.cs
Source/EasyNetQ.Tests/MessageVersioningTests/VersionedMessageSerializationStrategyTests.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/MessagePropertiesExtensions.cs
Source/EasyNetQ/MessageVersioning/MessageTypeProperty.cs

Also stop auto-converting byte[] to string back

Stop using string auto-conversion to byte[]

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/DelayedExchangeExtensions.cs
Source/EasyNetQ/DelayedExchangeScheduler.cs

Switch WithDelay to MessageProperties

---

Source/EasyNetQ/DefaultRpc.cs

Cache response exchange declaration

---

Source/EasyNetQ/Consumer/InternalConsumer.cs

Otherwise a model could be created without prefetch count set.

Dispose model if BasicQos failed

---

Source/EasyNetQ/DI/AsyncServiceResolverScope.cs
Source/EasyNetQ/DI/ConsumeScopeProviderExtensions.cs
Source/EasyNetQ/DI/IConsumeScopeProvider.cs
Source/EasyNetQ/DI/LightInjectAdapter.cs

I don't know why scopes haven't been implemented for LightInject.

Support scopes and IAsyncDisposable for LightInject

---

README.md
hall_of_fame.md

Hey team! I brought this idea from this repository: https://github.com/redis/go-redis
I thought it would be nice to have here :)
I'm also adding myself to hall of fame since I forgot to do it in my last contribution in #1244  🤦

Show contributors on readme

---

.github/workflows/ci.yml
.github/workflows/depsreview.yaml

https://github.com/EasyNetQ/EasyNetQ/pull/1643#issuecomment-1498123708

Switch to checkout@v3 and ubuntu-latest

---

Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/DefaultSendReceive.cs
Source/EasyNetQ/DelayedExchangeScheduler.cs
Source/EasyNetQ/MessagePropertiesExtensions.cs

Fixes #1589
PR rollbacks changes made in #1586 regarding headers.

Copy headers to address #1589

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Examples.DlxRetry/EntryPoint.cs
Source/EasyNetQ.Examples.PubSubWithAdvancedApi/EntryPoint.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_consumer_with_auto_ack.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_publish_to_non_existent_exchange.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_published_with_mandatory_and_with_publisher_confirms.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_pull_messages.cs
Source/EasyNetQ.IntegrationTests/Advanced/When_pull_messages_batch.cs
Source/EasyNetQ.Tests/RabbitAdvancedBusTests.cs
Source/EasyNetQ/AdvancedBusExtensions.Publish.cs
Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
Source/EasyNetQ/DefaultPubSub.cs
Source/EasyNetQ/DefaultRpc.cs
Source/EasyNetQ/DefaultSendReceive.cs
Source/EasyNetQ/DelayedExchangeScheduler.cs
Source/EasyNetQ/FuturePublishConfiguration.cs
Source/EasyNetQ/IAdvancedBus.cs
Source/EasyNetQ/Producer/ProducePipeline.cs
Source/EasyNetQ/PublishConfiguration.cs
Source/EasyNetQ/RabbitAdvancedBus.cs
Source/EasyNetQ/RequestConfiguration.cs
Source/EasyNetQ/SendConfiguration.cs

Closes https://github.com/EasyNetQ/EasyNetQ/issues/1082

Allow to configure publisher confirms per request

---

index.html

Also, drop the link to Code Rant blog.

Replace Google Group with GH Discussions

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ/Events/AckEvent.cs
Source/EasyNetQ/Events/ChannelRecoveredEvent.cs
Source/EasyNetQ/Events/ChannelShutdownEvent.cs
Source/EasyNetQ/Events/ConnectionBlockedEvent.cs
Source/EasyNetQ/Events/ConnectionCreatedEvent.cs
Source/EasyNetQ/Events/ConnectionDisconnectedEvent.cs
Source/EasyNetQ/Events/ConnectionRecoveredEvent.cs
Source/EasyNetQ/Events/ConnectionUnblockedEvent.cs
Source/EasyNetQ/Events/ConsumerModelDisposedEvent.cs
Source/EasyNetQ/Events/DeliveredMessageEvent.cs
Source/EasyNetQ/Events/MessageConfirmationEvent.cs
Source/EasyNetQ/Events/PublishedMessageEvent.cs
Source/EasyNetQ/Events/ReturnedMessageEvent.cs
Source/EasyNetQ/Events/StartConsumingFailedEvent.cs
Source/EasyNetQ/Events/StartConsumingSucceededEvent.cs
Source/EasyNetQ/Events/StoppedConsumingEvent.cs

To reduce amount of boilerplate code.

Convert events to records

---

.github/dependabot.yml

Group dependabot prs

---

Source/EasyNetQ.Tests/ConsumeTests/ConsumerTestBase.cs
Source/EasyNetQ.Tests/ConsumeTests/When_a_cancellation_error_occurs_in_the_message_handler.cs
Source/EasyNetQ.Tests/ConsumeTests/When_a_message_is_delivered_to_the_consumer.cs
Source/EasyNetQ.Tests/ConsumeTests/When_a_nack_received_from_the_message_handler.cs
Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
Source/EasyNetQ.Tests/ConsumeTests/When_cancellation_of_message_handler_occurs.cs
Source/EasyNetQ.Tests/ConsumeTests/When_consume_is_called.cs
Source/EasyNetQ.Tests/ConsumeTests/When_consume_is_called_with_auto_ack.cs
Source/EasyNetQ/ServiceRegisterExtensions.cs

HandleCancelledAsync should respect CancellationToken source

---

Source/EasyNetQ.ApprovalTests/EasyNetQ.Serialization.NewtonsoftJson.approved.txt
Source/EasyNetQ.ApprovalTests/EasyNetQ.Serialization.SystemTextJson.approved.txt
Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
Source/EasyNetQ.Examples.DlxRetry/EntryPoint.cs
Source/EasyNetQ.Examples.PubSubWithAdvancedApi/EntryPoint.cs
Source/EasyNetQ.Examples.Rpc/EntryPoint.cs
Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_publish_confirms_and_multi_channel_dispatcher.cs
Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_with_legacy_options.cs
Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_dead_letter_exchange.cs
Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_dead_letter_exchange_with_publish_confirms.cs
Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_dead_letter_exchange_with_topic.cs
Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_delayed_exchange.cs
Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_delayed_exchange_with_publish_confirms.cs
Source/EasyNetQ.Serialization.NewtonsoftJson/EasyNetQBuilderNewtonsoftExtensions.cs
Source/EasyNetQ.Serialization.SystemTextJson/EasyNetQBuilderSystemTextJsonExtensions.cs
Source/EasyNetQ.Serialization.Tests/EasyNetQBuilderSystemTextJsonExtensionsTests.cs
Source/EasyNetQ.Tests/MessageVersioningTests/MessageVersioningExtensionsTests.cs
Source/EasyNetQ/EasyNetQBuilderExtensions.cs

contributes to https://github.com/EasyNetQ/EasyNetQ/pull/1800

Use UseXxx for IEasyNetQBuilder extensions

---

Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
Source/EasyNetQ/Conventions.cs

Added ErrorQueueTypeConvention
Added ErrorExchangeTypeConvention
Added ErrorExchangeRoutingKeyConvention
All three added from Master branch.

Added ErrorQueueTypeConvention and two others to Conventions
