EasyNetQ/EasyNetQ

- Source/EasyNetQ/PersistentConnection.cs
A small thing, but we were seeing a lot of these messages in our logs, and I noticed the typo.
> Fix typo in 'Failed to connect' error message.

- Source/EasyNetQ/EasyNetQ.csproj
- Source/EasyNetQ/IBus.cs
- Source/EasyNetQ/Producer/IResponderConfiguration.cs
- Source/EasyNetQ/Producer/IRpc.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/EasyNetQ/RabbitBus.cs
Hi guys!
Here is a customization of rpc's respond side: prefetch count of responder's consumer.
It seems reasonable, because each responder in service can have different needs of prefetch count: very fast methods(hight prefetch count) or slow(with needs of better distribution between consumers).
What do you think about it?
> Responder prefetch count customization

- Source/EasyNetQ.Tests/ReflectionHelpersTests.cs
- Source/EasyNetQ/Conventions.cs
- Source/EasyNetQ/DeliveryModeStrategy.cs
- Source/EasyNetQ/ITimeoutStrategy.cs
- Source/EasyNetQ/ReflectionHelpers.cs
- Source/Version.cs
#354 
- Added `GetAttribute<TAttribute>` and updated `GetAttributes<TAttribute>` implementation to use the new backing store, used to be `ConcurrentDictionary<Type, Attribute[]>` and is now `ConcurrentDictionary<Type, Dictionary<Type, Attribute[]>>`.
- Added `Attribute` constraint on generic parameter of` GetAttribute<TAttribute>` and `GetAttribute<TAttribute>`.
- Updated all references of `GetAttributes<TAttribute>` to use `GetAttribute<TAttribute>` where a single element was retrieved from the resulting collection.
- `DefaultFactories<T>.Get()` now uses `Type.EmptyTypes` instead of instantiating an empty Type array. We'll also throw a `MissingMethodException` when we fail to retrieve a public parameterless constructor to mirror `Activator.CreateInstance<T>()` behavior where we used to …
> ReflectionHelpers-improvements

- Build/EasyNetQ.proj
- Package/EasyNetQ.Management.Client/EasyNetQ.Management.Client.nuspec
- Source/EasyNetQ.Management.Client/ManagementClient.cs
- Source/Version.cs
- hall_of_fame.md
- Remove dependency on specific version of Newtonsoft.Json for the Management Client by ILRepacking Newtonsoft.Json
- Default WebRequest.KeepAlive to false to resolve spurious 'the request was aborted: the request was canceled' exceptions when using management client with high frequency.
See also discussion in #365 regarding KeepAlive = false
> ManagementClient: Use ILRepack to intern Newtonsoft.Json, default WebRequest.KeepAlive to false

- Source/EasyNetQ/IBus.cs
- Source/EasyNetQ/Producer/ISendReceive.cs
- Source/EasyNetQ/Producer/SendReceive.cs
- Source/EasyNetQ/RabbitBus.cs
- Source/Version.cs
Adds support to `IBus`, `ISendReceive`, and their implementations for configuring the consumer properties via an `Action<IConsumerConfiguration>()`. This behavior already exists on other calls like `Subscribe()`.
This should allow for setting properties like `PrefetchCount` for `Receive()` consumers.
-----
*Original PR contents*
Opening this PR early to provide some context for discussion. I'm interested in configuring `PrefetchCount` for `Receive`/`Receive<T>` consumers, but there's no method override that supports that. A couple questions here:
1. Is this a reasonable approach?
2. Would you prefer a specific configuration builder over `IConsumerConfiguration` (like `ISubscriptionConfiguration` and `IResponderConfiguration`)?
- I'm really only concerned about `PrefetchCount`, so it'll …
> Ability to configure Receive() consumer behavior

- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/IConnectionFactory.cs
- Source/Version.cs
Needed distinct SSL options for each host configuration in a clustered
RabbitMQ environment. Before, you could only configure SSL options once
on the ConnectionConfiguration object. When you had multiple hosts
configured and the client attempted to connect to the next node in the
cluster, the connection would fail because the SSL ServerName property
didn't match. Now, you can configure SSL options on each Host object and
cycling the connection through the nodes uses the distinct SSL options.
closes #370
> SSL Enabled Cluster Support - Added SSL Options per Host Configuration

- Source/EasyNetQ/Conventions.cs
- Source/Version.cs
Hello, a simply fix on queue naming convention.
> When a subscriptionId is null the queue name end with '_'

- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/Integration/AdvancedBusTests.cs
- Source/EasyNetQ.Tests/Integration/ClientCommandDispatcherTests.cs
- Source/EasyNetQ.Tests/Integration/PersistentChannelTests.cs
- Source/EasyNetQ/PersistentConnection.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/Version.cs
Fix for #390 
- `PersistentConnection` now has a Initialize method which kicks off the `TryToConnect` loop. Checks have been added to make sure it's called only once per `PersistentConnection`.
- It was required to be able to have all `RabbitAdvancedBus` members correctly initialized before a connection is made. Since it's now possible to handle the first `OnConnected` event, it's also possible to use the bus directly from those event handlers. The `IPersistentConnection` and `IClientCommandDispatcher` in `RabbitAdvancedBus` were still null when the first `OnConnected` event was raised during `IPersistentConnection` instantiation. Thus we needed to make this a two step process to be able to assign members, then start connecting. This is the only place where we're instantiating a …
> Fix RabbitAdvancedBus auto connect

- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/Version.cs
hello, it's seem when the message broker connection is lost is not possible any more publish a message on queue EasyNetQ_Default_Error_Queue. I had the problem when the disconnection duration is longer than the heartbit duration, so in this case the ```ShutdownReport```on RabbitMQ.Client is gretar than 0 and the ```IConnection.Dispose``` will throw an exception.
> Bug fix publish message on  EasyNetQ_Default_Error_Queue

- Source/EasyNetQ/EasyNetQ.csproj
- Source/EasyNetQ/MessageDeliveryMode.cs
- Source/EasyNetQ/NonGeneric/NonGenericExtensions.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/EasyNetQ/Producer/SendReceive.cs
- Source/EasyNetQ/RabbitBus.cs
- Source/EasyNetQ/Scheduler.cs
- Source/EasyNetQ/Topology/Exchange.cs
- Source/EasyNetQ/Topology/ExchangeType.cs
- Source/Version.cs
- We now have a static class `MessageDeliveryMode` with constants to be used when setting `MessageProperties.DeliveryMode`, instead of hard coding 1 and 2 in multiple places for non-persistent and persistent mode. That was bugging me for a while but never got around changing it. :stuck_out_tongue:
- `ExchangeType` is the same kind of constant container and should never be instantiated, it's now static to enforce that.
- The default exchange returned by `Exchange.GetDefault` is now a static readonly member, so we won't be instantiated a new empty exchange on each call.
> Message delivery mode and misc

- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/Integration/RpcTests.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/Version.cs
#406 
We're now validating the the length of TReponse in `Rpc.Respond`. Note that the `Preconditions.CheckShortString` will actually never be hit because we'll be throwing in `TypeNameSerializer.Serialize` before.
I'll update the version number when #401 will be merged so I don't have to update it multiple times.
> Rpc silent fail fix

- Source/EasyNetQ/TypeNameSerializer.cs
- Source/Version.cs
Hey guys,
This is a proposal for the default `TypeNameSerializer` to store the result of its calls in ConcurrentDictionaries. The purpose is to improve the overall performance of the library by paying a small (unless you're using thousands of different types, which seems unlikely) price in terms of memory footprint.
Comparison for 100000 calls using a 3.2GHz i7:
| Serialize | Deserialize
------------ | ------------- | -------------
**Current implementation** | 138 ms | 501 ms
**Updated implementation** | 20 ms | 28 ms
**Change** | 79.7% decrease | 94.5% decrease
Nothing groundbreaking but I think that's nice to have. Feel free to tell me if you think we should keep the current implementation available and offer this one as opt in.
Will update version following your feedback and when other …
> typenameserializer uses ConcurrentDictionary

- Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
- Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/EasyNetQ/Scheduler.cs
This contains support for the new [priority queue feature](http://www.rabbitmq.com/priority.html) added in 3.5. I'll bump the version after #415 is merged since this is required to work.
Another small change committed along, in `RabbitAdvancedBus.QueueDeclare` we used `Int32.MaxValue` as default parameter values for `perQueueTtl` and `expire`, and would considered them only if they were different from this. This seemed a bit weird to me as these values could actually be used, although it wouldn't make a lot of sense, but still. I thought it was better to use nullables, and consider these argument only if an actual value was supplied.
> Priority queue support

- Package/EasyNetQ/EasyNetQ.nuspec
Lock this version to a supported version of RabbitMQ.Client
> No longer allows update to RabbitMq.Client 3.5.0

- Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs
- Source/Version.cs
I got the same problem.
I declared all my existing queues by `QueueDeclare` without `expires` parameter (`null` by default).
But `SubscribeAsync` [uses](https://github.com/EasyNetQ/EasyNetQ/blob/master/Source/EasyNetQ/RabbitBus.cs#L131) `int.MaxValue` as `expires` parameter.
> An attempt to fix #441

- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/Integration/PolymorphicRpc.cs
- Source/EasyNetQ.Tests/ProducerTests/When_a_ploymorphic_message_is_sent.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/Version.cs
Fix#468 and add integration test.  (Red->Green: Test failed before fix.)
@micdenny: I checked the rest of the codebase for similar uses of `Message<T>` where `IMessage<T>` might be preferred for same reason (support T polymorphic), but did not find any others.
> Fix #468 Polymorphic Request/Respond Does Not Work As Expected

- Source/EasyNetQ.Tests/ConnectionConfigurationTests.cs
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/Version.cs
Fixes #475.  Makes the `ConnectionConfiguration.Validate()` method idempotent with respect to configuring a Host from the `AMQPConnectionString` property.
An alternative evaluated was to ask whether `ConnectionConfiguration.Validate()` needs to be called twice by a connection codepath starting from `RabbitHutch.CreateBus(string connectionString ...)` overload.  However:
+ Various `ConnectionStringParserTests` clearly expect `ConnectionStringParser.Parse()` to invoke `ConnectionConfiguration.Validate()`.
+ The call to `ConnectionConfiguration.Validate()` made by the `RabbitHutch.CreateBus(ConnectionConfiguration connectionConfiguration, AdvancedBusEventHandlers advancedBusEventHandlers, Action<IServiceRegister> registerServices)` overload would seem to be necessary to be retained, in case …
> Fix Issue #475 -  AMQP-uri-specified connections get configured twice

- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/Version.cs
Extended the method signature of QueueDeclare and QueueDeclareAsync to put two more optional parameters at the end to allow specifying the maximum number of messages and/or the maximum size of the queue.
Fixes #472
> Allow specifying the maximum size of the message queue.

- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_with_subscription_configuration_attribute_no_expires.cs
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ/AutoSubscribe/AutoSubscriber.cs
- Source/EasyNetQ/AutoSubscribe/SubscriptionConfigurationAttribute.cs
- Source/Version.cs
I ran into an issue where wanting to change the prefetch count of a subscription, so I applied the ConfigurationSubscriptionAttribute:
[SubscriptionConfiguration(PrefetchCount = 1)]
public void Consume(MessageA message)
Additionally, this set the 'expires' property of the queue to `int.MaxValue`, which I think is counter intuitive (and causes problems for queues that were already declared before).
To solve this there are now 2 properties on the SubscriptionConfigurationAttribute, if anyone has suggestions for better ways/naming please let me know.
> Changed the default expires value of the autosubscriber attribute

- Source/EasyNetQ.Tests/ConnectionConfigurationTests.cs
- Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/Version.cs
For #448 Process will not always exit when handler throws error
Fix #448 Process hang when handler throws and bump version.cs
Refine fix #448
Clarify in unit test, what is stub (exists only to support the test) and
what is mock (something on which you assert expectations).
Fix #448 Process may not exit if handler throws
Fix further race conditions in DefaultConsumerErrorStrategy disposal.
Ensure all modifications to the connection variable are within locks.
If Connect() method holds lock, Dispose() will now let it finish making
connection, then Dispose() it.  If Dispose() method holds-then-releases
lock, when Connect() method acquires lock, it checks again if class is
disposing, before establishing a connection.
Refine fix #448 Process may hang if handler throws
Refine fix #448.  Update …
> Fix #448 Process may not exit if handler throws Exception

- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/PersistentConnectionTests.cs
- Source/EasyNetQ/PersistentConnection.cs
- Source/Version.cs
Fix #512 Process may hang due to PersistentConnection having the
potential to create a further AMQP connection, after it has been
disposed.
> Fix #512 Process may hang due to extra AMQP connection

- Source/EasyNetQ.Hosepipe/Program.cs
- Source/Version.cs
Had to make this change to get add support for error-queue name into the err and retry commands.
> Added custom queue-name support to 'err' and 'retry' commands

- Source/Version.cs
Disable CLS compliance, as hardly anything in the project is CLS compliant.
I think it's better to refactor everything to make it CLS compliant, or set the attribute to false.
> Disable CLS compliance

- Build/EasyNetQ.proj
- Package/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.nuspec
- Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
- Source/EasyNetQ.DI.LightInject/InjectionExtensions.cs
- Source/EasyNetQ.DI.LightInject/LightInjectAdapter.cs
- Source/EasyNetQ.DI.LightInject/LightInjectMessageDispatcher.cs
- Source/EasyNetQ.DI.LightInject/Properties/AssemblyInfo.cs
- Source/EasyNetQ.DI.LightInject/app.config
- Source/EasyNetQ.DI.LightInject/packages.config
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.DI.Tests/LightInjectAdapterTests.cs
- Source/EasyNetQ.DI.Tests/packages.config
- Source/EasyNetQ.sln
- Source/Version.cs
- hall_of_fame.md
Adds LightInject as a supported DI container (http://www.lightinject.net/). The code is mostly derived from the existing Ninject adapter.
I've also added a nuspec file and amended the build proj to package it. I wasn't sure if I was supposed to bump Version.cs, let me know if you want me to do this :)
This is using version 3.x of LightInject. Version 4.x targets .NET Core so would be dependent on #508
> Adds support for LightInject DI

- Source/EasyNetQ.Tests/ModelCleanupTests.cs
- Source/EasyNetQ/Producer/PersistentChannel.cs
- Source/Version.cs
Fixes #522. Removed call to `internalChannel.SafeDispose()` in `PersistentChannel`, since it occasionally causes blocking on broker reconnect. I have verified with RMQ developer @michaelklishin: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/154 that Disposing channel is not required.
For further details, see discussion on issue #522.
> Fix for #522

- Source/EasyNetQ/Producer/Rpc.cs
- Source/Version.cs
The RabbitMQ documentation on [federations](https://www.rabbitmq.com/federated-exchanges.html) states that the _default_ exchange can't be federated. The pull request uses the RPC exchange, declared by EasyNetQ, as a response exchange, which enables the usage of RPC over federated brokers.
> Use RPC exchange instead of default exchange for RPC reponses

- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/FluentConfiguration/PublishConfigurationTests.cs
- Source/EasyNetQ.Tests/Integration/PublishSubscribeTests.cs
- Source/EasyNetQ/EasyNetQ.projitems
- Source/EasyNetQ/FluentConfiguration/IPublishConfiguration.cs
- Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs
- Source/EasyNetQ/IBus.cs
- Source/EasyNetQ/RabbitBus.cs
- Source/Version.cs
Add support of [priority queues](https://www.rabbitmq.com/priority.html) to `IBus`.  Fix #494.
A failing integration test was added in ba961e7.  The test sends multiple messages with different priorities and expects that messages with higher priority will be received first.  Of course, the test doesn't actually set priorities in this commit but it does it in the final version.
A `priority` parameter was added  to `Publish` method of `IBus` in 90578e1 .
A `MaxPriority` property was added  to `SubscriptionConfiguration` in a63a4c8 .
> Message priority in IBus

- Source/EasyNetQ.Tests/ConnectionConfigurationTests.cs
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/IConnectionFactory.cs
- Source/Version.cs
Authentication via client certificates requires setting the ConnectionFactory AuthMechanism property. This PR adds an AuthMechanism property to the ConnectionConfiguration and passes it through to the ConnectionFactory.
The default AuthMechanism is set to PlainMechanism so it should not effect any existing users\code.
This will resolve #563 (without the additional documentation).
> Allow use of EXTERNAL authentication mechanism

- Source/EasyNetQ.DI.Tests/StructureMapAdapterWithRegistryTests.cs
- Source/EasyNetQ.Tests.Messages/Messages.cs
- Source/EasyNetQ.Tests.Tasks/Tasks/TestSimpleService.cs
- Source/EasyNetQ.Tests/ConventionsTests.cs
- Source/EasyNetQ.Tests/Integration/RequestResponseTests.cs
- Source/EasyNetQ/Conventions.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/Version.cs
As discussed here : https://groups.google.com/forum/#!topic/easynetq/BOlFOM3NZDo , here is the PR.
Added to convensions RpcRequest and RpcResponse naming conventions, so that you can configure them as needed.
The default for both has not changed thus this is not breaking change. I've created some tests (just say if the naming of the test messages is confusing).
> Added ability to configure RPC Exchange names based on request or response type.

- .gitignore
- Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
- Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/Version.cs
Bug fix: QueueDeclare does not allow an empty dead letter exchange. Because of this there is no straightforward way to configure a queue so that it dead letters messages to another fixed queue. Empty exchange name is a valid value and represents default RabbitMQ exchange and is used to target messages directly to a queue since all queues by default have a direct binding with this exchange.
fixes #602
> Bug fix: QueueDeclare does not allow an empty dead letter exchange

- Source/EasyNetQ.DI.SimpleInjector/SimpleInjectorMessageDispatcher.cs
- Source/Version.cs
- hall_of_fame.md
In Autofac this is possible. This is not possible with SimpleInjectorMessageDispatcher because it's private.
var subscriber = new AutoSubscriber(_bus, "prefix")
{
AutoSubscriberMessageDispatcher = new AutofacMessageDispatcher(container)
};
> Make SimpleInjectorMessageDispatcher public so it can be used with AutoSubscriber

- Source/EasyNetQ.Hosepipe/HosepipeConnection.cs
- Source/EasyNetQ.Hosepipe/Program.cs
- Source/EasyNetQ.Hosepipe/QueueParameters.cs
- Source/EasyNetQ.Hosepipe/Usage.txt
- Source/Version.cs
Hosepipe tool uses default port for connection to RabbitMQ broker.
Added support for custom port. 
Now it's possible to execute tool with host name and port **s:HostName:123** like this.
> Add RabbitMQ broker custome port support to hosepipe.

- Source/EasyNetQ.Hosepipe/ArgParser.cs
- Source/EasyNetQ.Hosepipe/ErrorRetry.cs
- Source/EasyNetQ.Hosepipe/HosepipeConnection.cs
- Source/EasyNetQ.Hosepipe/Program.cs
- Source/EasyNetQ.Hosepipe/QueueInsertion.cs
- Source/EasyNetQ.Hosepipe/QueueParameters.cs
- Source/EasyNetQ.Hosepipe/QueueRetrieval.cs
- Source/EasyNetQ.Hosepipe/Usage.txt
- Source/Version.cs
Refactored hosepipe broker customer port configuration. Now it's a new command line parameter 'sp' (server port).
> Hosepipe custom broker port configuration by separate parameter

- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/RabbitHutch.cs
On Core, remove the CreateBus API's that read the application config file. The user will need to pass in the connection string when creating a bus.
> Remove on Core the methods that read the application config file

- Build/EasyNetQ.proj
- Build/UpdateGitVersion.ps1
* Limiting NuGet packages that are created to the ones before
* EasyNetQ
* EasyNetQ.DI.*
* EasyNetQ.Serilog
* Updating dependencies in project.jsons to their updated versions so the packaged nupkg has the correct version
Note that the PR's CI build passed but was unable to run dotnet-gitversion successfully because PRs are run in a detached head state. When this PR is merged, the versions will be updated correctly like my build [here](https://ci.appveyor.com/project/conniey/easynetq).
@alinapopa @zidad @micdenny
> Fixing NuGet package creation

- Source/EasyNetQ.Tests/Integration/ConsumerShutdownTests.cs
- Source/EasyNetQ.Tests/Integration/SendReceiveIntegrationTests.cs
- Source/EasyNetQ.Tests/ModelCleanupTests.cs
- Source/EasyNetQ/IEventBus.cs
The [latest build](https://ci.appveyor.com/project/EasyNetQ/easynetq) failed because it reached a maximum of 60 minutes on the build server.  It appears to be because some of the tests have a AutoResetEvent.WaitOne call that will wait forever.
* Added a maximum TimeSpan to wait for a set event.  Test will fail if one was not received within that time span.
* Replaced a lock(object) with ConcurrentDictionary.AddOrUpdate.
> Fixing tests

- Source/EasyNetQ.Tests/ClientCommandDispatcherTests/When_an_action_is_invoked.cs
- Source/EasyNetQ.Tests/ClientCommandDispatcherTests/When_an_action_is_invoked_that_throws.cs
- Source/EasyNetQ/Producer/ClientCommandDispatcherSingleton.cs
- Source/Version.cs
Fix #623
Replace Client Command Dispatched Thread with critical section around `persistentChannel`.  I'm afraid that there was a special reason why the Client Command Dispatched Thread was implemented instead of critical section which I can't understand.
> Fix Client Command Dispatcher Thread hijacking

- Source/EasyNetQ/Consumer/ExclusiveConsumer.cs
- Source/EasyNetQ/Consumer/PersistentConsumer.cs
- Source/EasyNetQ/Consumer/TransientConsumer.cs
- Source/EasyNetQ/EasyNetQ.projitems
- Source/EasyNetQ/Events/StartConsumingFailedEvent.cs
- Source/EasyNetQ/Events/StartConsumingSucceededEvent.cs
- Source/Version.cs
Added StartConsumingFailedEvent and StartConsumingSucceededEvent. These
Events are fired by the consumer when it attempts to start consuming.
> Added Start Consuming Events

- Source/EasyNetQ.DI.SimpleInjector/SimpleInjectorAdapter.cs
- Source/Version.cs
- hall_of_fame.md
Pretty minor fix here, so I didn't bother opening up an issue.  Just trying to get in the hall_of_fame :D.  In the SimpleInjectorAdapter.Register method that takes a factory delegate, the delegate is being executed in the method instead of being deferred.  I believe I've made the appropriate fix.  Let me know your thoughts.
Thanks,
Brett J
> Bug fix in SimpleInjectorAdapter: defer execution of serviceCreator

- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/SystemMessages/Error.cs
- Source/Version.cs
This is to include queue name into Error Message. Queue name is retrieved from ConsumerExecutionContext.Info.Queue.
This is what we talked about in #681 
@micdenny
> Included queue name in Error message

- Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
- Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
- Source/Version.cs
The property UseBackgroundThreads was added to ConnectionConfiguration in a previous commit, but was never added as a connection string part.  Not sure if this is a patch or minor update from a sematic versioning stand point.  I've updated the minor, but let me know if we should change.
Thanks,
Brett
> Add useBackgroundThreads as connection string part

- Source/EasyNetQ.Tests/ConnectionConfigurationTests.cs
- Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/Version.cs
> Fix for incorrect port and vhost in logs for amqp/amqps connection strings

- Source/EasyNetQ/PersistentConnection.cs
- Source/Version.cs
When PersistentConnection.cs logs connection failures, it only logs the outer exception message. The outer exception often obfuscates the actual connection error captured by the inner exception. For connection errors debugging we are finding the outer exception much less helpful than inner exception, and I think we should surface the inner exception message when an inner exception is present.
> Connection error logging in PersistentConnection.cs not surfacing inner exception message

- Source/EasyNetQ/Producer/Rpc.cs
- Source/Version.cs
This fixes a bug where RPC would throw a timeout exception immediately, if timeout was set to 0 (= disabled).
Let me know if you want to merge this PR and if and what version I should bump...
Br
> RPC timer would end immediately if timeout was 0

- Build/EasyNetQ.proj
- Source/build.props
The issue is that using `dotnet pack` calls MSBuild Core, doesn't allow us to call GitVersionTask because it hasn't been ported to .NET Core.  As a result, the necessary GitVersion information is not propagated to the NuGet package.
This PR works around this by invoking the full .NET Framework MSBuild with the pack target.
Unfortunately, this will only work with a full installation of Visual Studio 2017.  It will not work on installations of Visual Studio 2017 Build Tools because the installer does not include:
* [.NET Core SDK](https://github.com/Microsoft/msbuild/issues/1697)
* [New NuGet targets (pack and restore)](https://github.com/NuGet/Home/issues/3660)
> Revert to full .NET Framework MSBuild for Pack target

- Source/EasyNetQ.Tests/FluentConfiguration/SubscriptionConfigurationTests.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ/FluentConfiguration/ISubscriptionConfiguration.cs
- Source/EasyNetQ/RabbitBus.cs
- hall_of_fame.md
When creating subscribers for very busy exchanges, it is helpful to be able to limit the maximum queue size as a number of messages or bytes, so that if the subscribers can't keep up for some reason, it doesn't further exacerbate the problem by running RabbitMQ out of resources, or creating an unmanageable backlog of messages.
> Added MaxLength and MaxLengthBytes options to fluent SubscriptionConfiguration

- Source/EasyNetQ/IConnectionFactory.cs
> Use specified connection name when creating new RabbitMQ connection

- Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
- Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
- Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
- Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
- Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
- Source/EasyNetQ.Hosepipe.SetupActions/EasyNetQ.Hosepipe.SetupActions.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
- Source/EasyNetQ.LogReader/EasyNetQ.LogReader.csproj
- Source/EasyNetQ.Scheduler.Mongo.Core/EasyNetQ.Scheduler.Mongo.Core.csproj
- Source/EasyNetQ.Scheduler.Mongo.Tests/EasyNetQ.Scheduler.Mongo.Tests.csproj
- Source/EasyNetQ.Scheduler.Mongo/EasyNetQ.Scheduler.Mongo.csproj
- Source/EasyNetQ.Scheduler.Tests/EasyNetQ.Scheduler.Tests.csproj
- Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
- Source/EasyNetQ.Serilog/EasyNetQ.Serilog.csproj
- Source/EasyNetQ.Tests.Common/EasyNetQ.Tests.Common.csproj
- Source/EasyNetQ.Tests.Tasks/EasyNetQ.Tests.Tasks.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Trace/EasyNetQ.Trace.csproj
- Source/EasyNetQ/EasyNetQ.csproj
- Source/build.targets
When there is no .git repository, GitVersionTask is unable to resolve Version information.  This adds a MSBuild Target to execute when the Version has not been set and sets the default Version.
Fixes #721 .
> Add SetDefaultVersion target

- Source/EasyNetQ.Scheduler.Mongo.Core/SchedulerService.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
- Source/EasyNetQ/Extensions.cs
- Source/EasyNetQ/Loggers/ConsoleLogger.cs
I wanted to add logging via log4net to my application.
I implemented `IEasyNetQLogger` interface according to [manual](https://github.com/EasyNetQ/EasyNetQ/wiki/Logging):
```csharp
public class EasyNetQLog4NetLogger : IEasyNetQLogger
{
private readonly ILog log;
public EasyNetQLog4NetLogger(string name)
{
log = LogManager.GetLogger(name);
}
public void DebugWrite(string format, params object[] args)
{
log.DebugFormat(format, args);
}
public void InfoWrite(string format, params object[] args)
{
log.InfoFormat(format, args);
}
public void ErrorWrite(string format, params object[] args)
{
log.ErrorFormat(format, args);
}
public void ErrorWrite(Exception exception)
{
log.Error(exception.Message, exception);
}
}
```
And when my handler threw an exception, I got the following error message in …
> Added braces escaping for non-format format string

- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ/Producer/Rpc.cs
Fixes an issue where a cancelled task would neither be acknowledged nor responded to.
This could occur if the responder threw a TaskCanceledException.
https://github.com/EasyNetQ/EasyNetQ/issues/111
> Issue #111: A responder whose task is cancelled will still respond and ACK

- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
The bug fix in this method has made the Connect method pretty long. It would be nice to just inherit from this class and just be able to override HandleConsumerError(), and change some code in there. As the class is not sealed, and has a couple virtual methods, lets make Connect() protected!
> Allow subclasses of DefaultConsumerErrorStrategy to call connect method

- Source/EasyNetQ/Consumer/InternalConsumer.cs
Synchronous disposal of internal consumer allows to clean up created queues with ifunused = true option without any race condition (see https://github.com/EasyNetQ/EasyNetQ/issues/766)
> Make disposal of InternalConsumer synchronous (#766)

- Source/EasyNetQ/JsonSerializer.cs
Because we don't merge Newtonsoft.Json anymore, we can create constructor which accepts JsonSerializationSettings.
> Allow to pass JsonSerializerSettings to JsonSerializer

- .gitignore
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_async.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_async_with_subscription_configuration.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_async_with_subscription_configuration_action.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_async_with_subscription_configuration_action_and_attribute.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_autosubscribing_with_explicit_implementation.cs
- Source/EasyNetQ.sln.DotSettings
- Source/EasyNetQ/AutoSubscribe/AutoSubscriber.cs
- Source/EasyNetQ/AutoSubscribe/AutoSubscriberConsumerInfo.cs
not using attributes for queue naming because of rename to ConsumeAsync.
Fixes https://github.com/EasyNetQ/EasyNetQ/issues/817
> Add hotfix for AutoSubscriber configuration

- Source/EasyNetQ.Tests/ConsumeTests/ConsumerTestBase.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_has_multiple_handlers.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_is_cancelled_by_the_broker.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_is_cancelled_by_the_user.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_message_is_received.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_polymorphic_message_is_delivered_to_the_consumer.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_an_error_occurs_in_the_message_handler.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_cancellation_of_message_handler_occurs.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_cancelled.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_executed.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_failed.cs
- Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
- Source/EasyNetQ/Consumer/ConsumerDispatcher.cs
- Source/EasyNetQ/Consumer/ConsumerExecutionContext.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
Related issues are #723 and #758.
It seems we have concurrency issue connected with usage of IModel from multiple threads:
1. One thread is Consumer Dispatcher Thread
2. During sending acks to messages model can be used from multiple thread pool threads.
It will happen more likely if `IAdvancedBus.ConsumeAsync` is used, because if not - messages will be processed one by one and acks will be sent one by one too. But in case of using `IAdvancedBus.ConsumeAsync` messages will be acked in parallel from thread pool threads.
Acking of messages in parallel does not cause an issue itself(or I can't reproduce). It causes an issue only with combination of disposing IModel from Consumer Dispatcher Thread(it can happen because of disconnect or manual disposal of subscription).
Also increasing …
> Ack on model should be called from Consumer Dispatcher Thread

- Source/EasyNetQ.Tests/EventBusTests.cs
- Source/EasyNetQ/Consumer/ExclusiveConsumer.cs
- Source/EasyNetQ/Consumer/PersistentConsumer.cs
- Source/EasyNetQ/Consumer/PersistentMultipleConsumer.cs
- Source/EasyNetQ/Consumer/TransientConsumer.cs
- Source/EasyNetQ/IEventBus.cs
- Source/EasyNetQ/Internals/Timers.cs
- Source/EasyNetQ/PersistentConnection.cs
The goal of this PR was to fix #762, but there are several unrelated changes:
1. Return type of `IEventBus.Subsribe` was changed from `CancelSubscription` delegate to `IDisposable`.
2. Usage of `Timer` in `PersistentConnection` was refactored.
> Simplify usages of timer and change disposal of IEventBus's subscription

- Source/EasyNetQ.DI.StructureMap/StructureMapAdapter.cs
- Source/EasyNetQ.DI.Tests/StructureMapDependencyScopeTests.cs
This adds correct implementation of IServiceResolverScope for StructureMap container. Transient instances are now disposed of when we finish handling message in `DefaultAutoSubscriberMessageDispatcher.Dispatch`
> Auto subscribe: Create nested container per message handled for StructureMap

- Source/EasyNetQ.Tests/Mocking/MockBuilder.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
This PR does three things:
1. Allows you to declare a server-named queue through the existing `QueueDeclare` and `QueueDeclareAsync` overloads (by specifying an empty `name`). This was already allowed, but would return back a `Queue` with a blank name. I guess this was a bug?
2. Adds an async alternative to `QueueDeclare()`; `QueueDeclareAsync()`
3. Changes the implementation of the existing `QueueDeclare()` method to call into the overload with parameters.
Was this an oversight, or is my thinking wrong here?
> Add ability to declare transient server-named queues asynchronously

- Source/EasyNetQ.Tests/MessageFactoryTests.cs
- Source/EasyNetQ/IMessage.cs
- Source/EasyNetQ/Preconditions.cs
This prevents structs from being used as message bodies, which sounds like an unnecessary limitation.
> Remove class constraint

- Source/EasyNetQ.DI.Microsoft/ServiceCollectionAdapter.cs
- Source/EasyNetQ.DI.StructureMap/StructureMapAdapter.cs
- Source/EasyNetQ.DI.Tests/MicrosoftDependencyScopeTests.cs
- Source/EasyNetQ.DI.Tests/StructureMapDependencyScopeTests.cs
- Source/EasyNetQ.Tests/MessageFactoryTests.cs
- Source/EasyNetQ.Tests/Mocking/MockBuilder.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/IMessage.cs
- Source/EasyNetQ/Preconditions.cs
- Source/EasyNetQ/Producer/Rpc.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
> EasyNetQ 3.3.1

- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
Using the Abstractions doesn't force users to use a particular implementation version of Microsoft's DI.
This is how it's done in other libraries as well, including Microsoft's projects. 
Examples: https://github.com/aspnet/Caching/blob/master/src/Microsoft.Extensions.Caching.Memory/Microsoft.Extensions.Caching.Memory.csproj
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.AspNetCore/project.json
> Use Abstractions for Microsoft DI

- Source/EasyNetQ/Consumer/ConsumerCancellation.cs
- Source/EasyNetQ/Consumer/ExclusiveConsumer.cs
- Source/EasyNetQ/Consumer/PersistentConsumer.cs
- Source/EasyNetQ/Consumer/PersistentMultipleConsumer.cs
- Source/EasyNetQ/Consumer/TransientConsumer.cs
Replaces #862 from @rtaylor01:
Added a ConsumerCancelled event to the ConsumerCancellation class which will be invoked whenever a consumer is canceled by the broker. The idea is that if an app is consuming a queue using the EasyNetQ Comsume() method, it will need to act on the ConsumerCancelled event if the broker cancels the consumer. A simple example of this is when the queue is deleted using RabbitMQ management website while the app is consuming the queue. If there is no notification that the consumer is canceled, the app thinks it is still waiting for a message to be delivered on the queue.
> Created ConsumerCancelled event on ConsumerCancellation

- Source/EasyNetQ.Tests/Integration/RequestResponseTests.cs
- Source/EasyNetQ.Tests/Integration/RpcTests.cs
- Source/EasyNetQ.Tests/Integration/RpcWithLegacyConventionsTests.cs
- Source/EasyNetQ/ConventionsExtensions.cs
- Source/EasyNetQ/LegacyRpcConventions.cs
- Source/EasyNetQ/LegacyRpcConventionsExtensions.cs
- Source/EasyNetQ/Producer/Rpc.cs
fixes #677 
rework of #738 
now you can switch to legacy conventions simple doing this:
```csharp
var bus = RabbitHutch.CreateBus("host=localhost", x => x.EnableLegacyConventions());
```
that is a shorcut of:
```csharp
var bus = RabbitHutch.CreateBus("host=localhost", x => x
.EnableLegacyTypeNaming()
.EnableLegacyRpcConventions());
```
with this legacy convention enabled, both pubsub and rpc can work between old and new easynetq version, and also you can upgrade to the latest version without having to migrate all the persisted queues and exchanges on rabbitmq server.
Thanks to @xpicio for the initial work #738 !!
> Legacy RPC conventions

- Source/EasyNetQ.Tests/MessageVersioningTests/MessageVersionStackTests.cs
- Source/EasyNetQ.Tests/MessageVersioningTests/MyMessageV3.cs
- Source/EasyNetQ/MessageVersioning/MessageVersionStack.cs
I stumbled upon a problem with how MessageVersionStack works when there are more than two versions of a message. This behavior was seen on EasyNetQ version 3.3.5, and the latest develop seems to have no changes to the relevant code, so most likely it exists there as well.
The problem: If you have three versions of a message, i.e. MyMessage, MyMessageV2 and MyMessageV3, you've got a subscriber for each of them, and publish MyMessageV3, only MyMessageV3 and MyMessage are received, MyMessageV2 never arrives.
I traced the root of the problem into how versioned exchanges are declared and bound to each other. The exchange for MyMessageV3 is bound to the relevant queues and into the exchange of MyMessage, but not into the exchange of MyMessageV2, which it should do as well. The reason for this …
> Fix MessageVersionStack to work with more than 2 versions

- Source/EasyNetQ.Tests/MessageVersioningTests/MessageVersionStackTests.cs
- Source/EasyNetQ/MessageVersioning/MessageVersionStack.cs
MessageVersionStack.GetSupersededType uses Type.GetInterfaces which does not
offer any order guarantees. When selecting the superseded type for a message, we could sort
by class name, but that would just introduce a limitation on message naming.
Instead of that, let's call GetInterfaces for type and type.BaseType, and grab the ISupersede
entries from those. The one that does not exist in base type's list is the correct superseded type.
> Make GetSupersededType work with any message version hierarchy

- Source/EasyNetQ.Hosepipe.Tests/ErrorMessageRepublishSpike.cs
- Source/EasyNetQ.Hosepipe/ErrorRetry.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_has_multiple_handlers.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_polymorphic_message_is_delivered_to_the_consumer.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ.Tests/DefaultMessageSerializationStrategyTests.cs
- Source/EasyNetQ.Tests/Integration/ConsumerErrorConditionsTests.cs
- Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ.Tests/JsonSerializerTests.cs
- Source/EasyNetQ.Tests/MessageVersioningTests/VersionedMessageSerializationStrategyTests.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
- Source/EasyNetQ/DefaultMessageSerializationStrategy.cs
- Source/EasyNetQ/IMessage.cs
- Source/EasyNetQ/ISerializer.cs
- Source/EasyNetQ/JsonSerializer.cs
- Source/EasyNetQ/MessageVersioning/VersionedMessageSerializationStrategy.cs
- Source/EasyNetQ/Producer/Rpc.cs
The PR is related to #865.
RPC depends on the hack with `Newtonsoft.JSON` which can be fixed. 
It breaks the backward compatibility a bit(only if a custom `ISerializer` was created), but there is no serialization incompatibility here. It will be nice to ship PR as `3.4`, but may be `3.3.10` is enough.
PS @sungam3r Please review the PR too.
> Remove newtonsoft hack from rpc

- Source/EasyNetQ/Producer/PubSubExtensions.cs
- Source/EasyNetQ/Producer/RpcExtensions.cs
- Source/EasyNetQ/Producer/SendReceiveExtensions.cs
- Source/EasyNetQ/Scheduling/SchedulerExtensions.cs
moved extensions methods under the same namespace as IBus to help developers easily discover all the public interface
now we can find methods like `bus.PubSub.PublishAsync(T message)` right away importing only `EasyNetQ` namespace that is the minimum requirements to create a bus and now also to use all the public interface provided also from extensions methods along with the interface.
> Moved extensions methods under the same namespace as IBus

- Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
- Source/EasyNetQ.Tests/Integration/AdvancedApiExamples.cs
- Source/EasyNetQ.Tests/Integration/AdvancedBusTests.cs
- Source/EasyNetQ/AdvancedBusExtensions.cs
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/Producer/DefaultPubSub.cs
- Source/EasyNetQ/Producer/DefaultRpc.cs
- Source/EasyNetQ/QueueDeclareConfiguration.cs
- Source/EasyNetQ/QueueMode.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/EasyNetQ/Scheduling/DeadLetterExchangeAndMessageTtlScheduler.cs
It's very hard to extend the way how queues are declared.
``` 
Task<IQueue> QueueDeclareAsync(
string name,
bool passive = false,
bool durable = true,		
bool exclusive = false,		
bool autoDelete = false,		
int? perQueueMessageTtl  = null,		
int? expires = null,		
int? maxPriority = null,		
string deadLetterExchange = null,		
string deadLetterRoutingKey = null,		
int? maxLength = null,		
int? maxLengthBytes = null,		
CancellationToken cancellationToken = default
);
```
The PR proposes the fluent configuration of declaration as it was done in case of publish and consume. Also it introduces `Lazy Queue` declaration.
PS I had to split passive declaration to separate method.
> Rework queue declaration. LazyQueue is introduced.

- Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
- Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
- Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
- Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
- Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
- Source/EasyNetQ.DI.Tests/ContainerAdapterTests.cs
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
- Source/EasyNetQ.LogReader/EasyNetQ.LogReader.csproj
- Source/EasyNetQ.Scheduler.Mongo.Core/EasyNetQ.Scheduler.Mongo.Core.csproj
- Source/EasyNetQ.Scheduler.Mongo.Tests/EasyNetQ.Scheduler.Mongo.Tests.csproj
- Source/EasyNetQ.Scheduler.Mongo/EasyNetQ.Scheduler.Mongo.csproj
- Source/EasyNetQ.Scheduler.Tests/EasyNetQ.Scheduler.Tests.csproj
- Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
- Source/EasyNetQ.Tests.Common/EasyNetQ.Tests.Common.csproj
- Source/EasyNetQ.Tests.Tasks/EasyNetQ.Tests.Tasks.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Trace/EasyNetQ.Trace.csproj
- Source/EasyNetQ/EasyNetQ.csproj
- docker-compose.yaml
Updated:
- Autofac 4.6.1
- LightInject 5.5.0
- Ninject 3.3.4
- SimpleInjector 3.2.7
- RabbitMQ 5.1.1
breaking: Minimal .NET version is now 4.5.2 for mongodb libraries
> Bump dependencies

- Source/EasyNetQ.Tests/Integration/PublisherConfirmsIntegrationTests.cs
- Source/EasyNetQ/Producer/PublishConfirmationListener.cs
- Fix Publisher Confirmation timeout
Issue is that the IModel object reference on the @event in OnMessageConfirmation has changed. So it has the same ChannelNumber but it is a dfferent object
> Fix publisher confirmation bug

- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
- Source/EasyNetQ.LogReader/EasyNetQ.LogReader.csproj
- Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ/EasyNetQ.csproj
The PR updates `RabbitMQ.Client` to latest `5.*` (and also excludes `6.*` from supported versions because it breaks the compilation) version and to latest `LibLog`.
> Bump RabbitMQ.Client to 5.2.0 and LibLog to 5.0.8

- Source/EasyNetQ/ConnectionConfiguration.cs
Should show on RabbitMq connection details:
[if run on dotnet core 3.1.3]
**net_version | 3.1.3**
> Add Net Version to ClientProperties

- Source/EasyNetQ.Tests/DefaultMessageSerializationStrategyTests.cs
- Source/EasyNetQ/IMessage.cs
- Source/EasyNetQ/MessageFactory.cs
Upon exception the response message's body was always 'null' since the message was created using an empty constructor. Now the constructor with a type argument is used. To it an instance of the type of the response message is passed. This allows the publisher to receive the incurred exception.
Resolves #987
PS It's a replacement of https://github.com/EasyNetQ/EasyNetQ/pull/1002
> Exception in consumer not propagating to producer

- Source/EasyNetQ/Consumer/ConsumerDispatcher.cs
- Source/EasyNetQ/Consumer/IConsumerDispatcher.cs
Related to #1043.
So, it seems that #1021 should be released with major version bump, we could remove `QueueAction(Action)` as well.
Also this PR covers a very weird situation when action throws OCE.
> Drop `IConsumerDispatcher.QueueAction(Action)`

- Source/EasyNetQ/ConnectionConfigurationExtensions.cs
- Source/EasyNetQ/Producer/PersistentChannel.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
Fix #1010
Also, this PR fixes a very rare situation when Publish tells that message is published, but actually, it is not.
PS All versions of sleep(async Thread.Sleep or async Task.Delay) work fine with `InfiniteTimeSpan`.
> Allow infinite timeout with publish confirms

- Source/EasyNetQ/JsonSerializer.cs
Fix #974
Most of the code is from Newtonsoft.JSON, but:
1. We need to return bytes, so StreamWriter+MemoryStream is used instead of StringWriter+StringBuilder.
2. UTF8 without BOM is used because it is how serialization worked before(BOM was not emitted).
> Use own JSON serializer instead of a static one

- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/NuGet.Config
- appveyor.yml
1. Upgrade from 2017 to 2019 image
2. Bump netcore2 to netcore3
3. Remove feature and release branches specific configurations
> Bump base image and simplify configuration

- Source/EasyNetQ/Conventions.cs
- Source/EasyNetQ/QueueAttribute.cs
- Source/EasyNetQ/ReflectionHelpers.cs
Eliminates memory allocation for empty `QueueAttribute` on each exchange/queue declaration.
> Add QueueAttribute.Default

- Source/EasyNetQ.Tests/ConsumeTests/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
This bug was introduced in #997: ConfirmSelect must be called on IModel before waiting for confirms.
FYI @Rotvig
> Add missing ConfirmSelect

- Source/EasyNetQ.IntegrationTests/DockerProxy.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_polymorphic.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_default_options.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_exclusive.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_priority.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_publish_confirms.cs
- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_topic.cs
- Source/EasyNetQ.IntegrationTests/RabbitMQFixture.cs
- Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_polymorphic.cs
- Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_with_default_options.cs
- Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_with_legacy_options.cs
- Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_with_publish_confirms.cs
- Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_dead_letter_exchange.cs
- Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_dead_letter_exchange_with_publish_confirms.cs
- Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_delayed_exchange.cs
- Source/EasyNetQ.IntegrationTests/Scheduler/When_future_publish_using_delayed_exchange_with_publish_confirms.cs
- Source/EasyNetQ.IntegrationTests/SendReceive/When_send_receive_with_default_options.cs
- Source/EasyNetQ.IntegrationTests/SendReceive/When_send_receive_with_multiple_message_types.cs
- Source/EasyNetQ.IntegrationTests/SendReceive/When_send_receive_with_publish_confirms.cs
- Source/EasyNetQ.IntegrationTests/Utils/ManagementClientExtensions.cs
- Source/EasyNetQ.IntegrationTests/settings.json
- Source/EasyNetQ/Consumer/InternalConsumer.cs
https://github.com/EasyNetQ/EasyNetQ/issues/330#issuecomment-632904466
We have an issue with consumers reconnections which was caused by https://github.com/EasyNetQ/EasyNetQ/pull/1021.
If a connection is closed for any reason(it could be closed in management API or even by broker restart) all models will be closed with ModelShutdown as well.
Thanks to @EduardoPires for reporting.
FYI @Rotvig @sungam3r
> Fix consumers reconnection

- Source/EasyNetQ.Tests/ConnectionConfigurationTests.cs
- Source/EasyNetQ.Tests/Integration/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/ConnectionConfigurationExtensions.cs
- Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
- Source/EasyNetQ/ConnectionString/IConnectionStringParser.cs
- Source/EasyNetQ/DI/ConnectionFactoryFactory.cs
- Source/EasyNetQ/RabbitHutch.cs
- Source/EasyNetQ/ServiceRegisterExtensions.cs
Fixes #986
It seems that:
1. ContinuationTimeout should be set to Timeout
1. NetworkRecoveryInterval should be set to ConnectIntervalAttempt
Also, PR removes properties which are shown by default in management plugin UI:
1. version
1. connected
1. user
1. requested_hearbeat
In addition, XML docs are added.
> Fix client name and clean up configuration

- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
As discussed [here](https://github.com/EasyNetQ/EasyNetQ/issues/1068). I haven't found any tests covering logging so didn't change anything.
> Issue 1068: Move logging from HandlerRunner to DefaultConsumerErrorStrategy

- Source/EasyNetQ.IntegrationTests/Advanced/When_published_with_mandatory_and_with_publisher_confirms.cs
- Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
- Source/EasyNetQ.Tests/ProducerTests/PublishConfirmationListenerTest.cs
- Source/EasyNetQ/Events/MessageConfirmationEvent.cs
- Source/EasyNetQ/Events/PublishedMessageEvent.cs
- Source/EasyNetQ/Events/ReturnedMessageEvent.cs
- Source/EasyNetQ/Producer/IPublishPendingConfirmation.cs
- Source/EasyNetQ/Producer/MessagePropertiesExtensions.cs
- Source/EasyNetQ/Producer/MessageReturnedException.cs
- Source/EasyNetQ/Producer/PersistentChannel.cs
- Source/EasyNetQ/Producer/PublishConfirmationListener.cs
- Source/EasyNetQ/Producer/PublishInterruptedException.cs
- Source/EasyNetQ/Producer/PublishNackedException.cs
- Source/EasyNetQ/Producer/PublishReturnedException.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
Fixes #537
In case of enabled publisher confirms, we could observe a message was neither acknowledged nor rejected because it was returned. 
PR helps to not receive a timeout in case of a returned message(as mentioned in #537) but to receive a proper exception that indicates that a message was returned. Unfortunately, it's impossible to match a published message with a returned message by delivery tag, because there is no delivery tag in returned message info, but we could attach it manually to headers.
> Improve mandatory flag support in case of enabled publisher confirms

- Source/EasyNetQ/Consumer/ConsumerDispatcher.cs
We have the issue when doing deployment of our service we get ArgumentExceptions in the log because it is thrown from .TakeFromAny - so i replaced it with TryTakeFromAny which does not throw this exception
> Fix Argument exception is thrown on dispose of consumer dispatcher

- Source/EasyNetQ/MessageProperties.cs
Hi, there is an issue with the serialization & deserialization of a message. When a message has an empty header (which is default) it is deserialized as null, but a flag `basicProperties.IsHeadersPresent()` returns true, but `Header` is `null`. Which causes silent death.
Deserialization of header as null: https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/2a709aa76f25e8b6754cef4e4f482547d6c1d870/projects/RabbitMQ.Client/client/impl/WireFormatting.cs#L211
Iterating over null: https://github.com/EasyNetQ/EasyNetQ/blob/master/Source/EasyNetQ/MessageProperties.cs#L46
This PR change how a message is serialized ->header is not serialized if is empty. `basicProperties.IsHeadersPresent()` returns `false` and everything is shiny.
> Do not send empty header (incompatible with RabbitMq.Client)

- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
- Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
- Source/EasyNetQ.Scheduler/EasyNetQ.Scheduler.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/MessagePropertiesTests.cs
- Source/EasyNetQ.Tests/TestMessage.cs
- Source/EasyNetQ/EasyNetQ.csproj
- Source/EasyNetQ/MessageProperties.cs
Fix #1109
A bit weird case when `IsHeadersPresent` returns true, but `Headers` is null :-/
Changes:
1. All necessary xml docs are added
1. It implements IClonable
1. *Present fields are read-only
1. HeadersPresent property is true only if headers != null && headers.Count > 0
1. Headers property is lazily initialized
1. Nice code formatting :-/
Also this PR limits compatibility with RabbitMQ.Client from major to minor to reduce complaints caused by updates between minor versions of RabbitMQ.Client.
> Refactoring of MessageProperties for compatibility with latest RabbitMQ.Client 

- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
It allows to use the package with Asp.Net Core < 2.2
Fixes #1139
> Downgrade Microsoft.Extensions.DependencyInjection to 2.0

- Source/EasyNetQ.Tests/ConnectionString/AmqpConnectionStringParserTests.cs
- Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/ConnectionString/AmqpConnectionStringParser.cs
- Source/EasyNetQ/ConnectionString/CompositeConnectionStringParser.cs
- Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
- Source/EasyNetQ/ConnectionString/ConnectionStringParser.cs
- Source/EasyNetQ/ConnectionString/IConnectionStringParser.cs
- Source/EasyNetQ/EasyNetQ.csproj
- Source/EasyNetQ/Internals/UriExtensions.cs
- Source/EasyNetQ/ServiceRegisterExtensions.cs
Fixes #1151, #1086
The goal of the PR is to support this kind of connection string:
`amqp://user:pass@host:10000/vhost?persistentMessages=false&prefetchCount=2&timeout=1&publisherConfirms=true&name=unit-test&mandatoryPublish=true&connectIntervalAttempt=2&product=product&platform=platform`
`ConnectionConfiguration.AmqpConnectionString` is deprecated and preferred way to get `ConnectionConfiguration` from amqp connection string is to call `ConnectionStringParser.Parse`.
Also it fixes support of `amqps` connection strings.
> Enhanced support of amqp connection string

- Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
- Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
- Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
- Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
- Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
- Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
- Source/EasyNetQ/EasyNetQ.csproj
- Source/build.props
```
warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead
```
```
warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```
> Fix NuGet deprecation warnings

- Source/EasyNetQ/ConnectionString/ConnectionStringParser.cs
`SetDefaultProperties` will be called for `ConnectionConfiguration` [here](https://github.com/EasyNetQ/EasyNetQ/blob/develop/Source/EasyNetQ/RabbitHutch.cs#L174), so there is no need to call it anywhere else.
> Do not call SetDefaultProperties twice

- Source/EasyNetQ.Tests/ConsumeTests/DefaultConsumerErrorStrategyTests.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_an_error_occurs_in_the_message_handler.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_cancellation_of_message_handler_occurs.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_cancelled.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_executed.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_failed.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
- Source/EasyNetQ/Consumer/IConsumerErrorStrategy.cs
Hello,
I would like to create a custom `IConsumerErrorStrategy` with `await work(cancellationToken);`
Now it is possible only over `work().ConfigureAwait(false).GetAwaiter().GetResult()`.
> Make IConsumerErrorStrategy methods async

- Source/EasyNetQ.Tests/ConnectionString/AmqpConnectionStringParserTests.cs
- Source/EasyNetQ/ConnectionString/AmqpConnectionStringParser.cs
Fixing problem when connection string contains special characters.
> Fix missing unescape in AmqpConnectionStringParser

- Source/EasyNetQ.IntegrationTests/PubSub/When_publish_and_subscribe_with_queue_type.cs
- Source/EasyNetQ.Tests/ConventionsTests.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ.Tests/TestMessage.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
- Source/EasyNetQ/Conventions.cs
- Source/EasyNetQ/DefaultPubSub.cs
- Source/EasyNetQ/QueueAttribute.cs
Hello,
Based on my previous issue (https://github.com/EasyNetQ/EasyNetQ/issues/1241),
This is my first pull request to this repository, I'd like to start using EasyNetQ but currently the project doesn't have fully implemented quorum queues, so I decided to contribute finishing implementing them :)
Important change note:
Currently, it's not possible to **use** quorum queues with the actual implementation existent on EasyNetQ source code, it's only possible to **create** them, but not subscribe. The reason for that is, in the InternalConsumer the prefetch configuration is set to global = true and it's impossible to use quorum queues with that configuration (reference: https://www.rabbitmq.com/consumer-prefetch.html) then I changed to global = false, which according to rabbitMq documentation …
> Improve quorum queues implementation

- Source/EasyNetQ/AutoSubscribe/AutoSubscriber.cs
- Source/EasyNetQ/SubscriptionConfiguration.cs
If no topic attribute set to IConsumeAsync method a broadcast routing key # will not be added for message broadcasting
> [routing fix] broadcast exchange routing key skip for empty TopicAttr

- Source/EasyNetQ.Tests/PersistentChannelTests/When_an_action_is_performed_on_a_broken_channel.cs
- Source/EasyNetQ/Producer/AmqpErrorCodes.cs
- Source/EasyNetQ/Producer/PersistentChannel.cs
Fixes #1249, #1248.
It doesn't look like we are able to do something with connection disruptions, but we are able to handle these events gracefully.
> In case of internal errors reopen a channel and try again

- Source/EasyNetQ/ConnectionConfiguration.cs
- Source/EasyNetQ/DI/ConnectionFactoryFactory.cs
- hall_of_fame.md
I implemented max channel handling support to solve my problem I described in #1224 
User can set max supported channels by client and limit the creation of new channels like this:
```
var rabbitConfig = new ConnectionConfiguration
{
...
RequestedChannelMax = 1
..
};
RabbitHutch.CreateBus(rabbitConfig, sr => { });
```
**How it works:**
If max supported channel limit is reached EasyNetQ returns the last created channel for any new requested channel. 
**Potential problems/side effects**
This can potentially create problems when developers are not aware that multiple queues can be connected to the same channel. However the current solution is also not perfect since when the limit is reached it stops creating new queues silently. So I believe we trade one side effect with another in this edge …
> Max channel handling support

- Source/EasyNetQ/PersistentConnection.cs
@micdenny found that in v7 EasyNetQ doesn't log anything on PersistentConnection dispose.
I've investigated and found that because of the unsubscription from events before calling Dispose this log is lost.
As a solution, we previously agreed to dispose firstly and then unsubscribe from events. These works only for `            connection.RecoverySucceeded -= OnConnectionRecovered;`, for other events it's prohibited to unsubscribe from them after a connection disposal.
```
Object name: 'RabbitMQ.Client.Framing.Impl.AutorecoveringConnection'.
at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.remove_ConnectionUnblocked(EventHandler`1 value)
at EasyNetQ.PersistentConnection.DisposeConnection() in /Users/yury.pliner/Sources/EasyNetQ/Source/EasyNetQ/PersistentConnection.cs:line 155
at …
```
> Fix connection close logging

- Source/EasyNetQ/Interception/GZipInterceptor.cs
- Source/EasyNetQ/Interception/TripleDESInterceptor.cs
This code was moved from #1277 to make review easier.
> Eliminate ROM.ToArray() heap allocation in GZipInterceptor and TripleDESInterceptor

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/DefaultPubSub.cs
- Source/EasyNetQ/DefaultSendReceive.cs
- Source/EasyNetQ/ReceiveConfiguration.cs
- Source/EasyNetQ/SubscriptionConfiguration.cs
- hall_of_fame.md
I added the possibility to set "QueueType" parameter on Send Receive configuration.
In the process I also made the update to set the parameter "Single Active Consumer" (x-single-active-consumer) for PubSub (SubscriptionConfiguration) (as discussed in #1282 ).
> Added QueueType Parameter on Send / Receive (ReceiveConfiguration) & Single Active Consumer for PubSub (SubscriptionConfiguration)

- Source/EasyNetQ/Persistent/PersistentConnection.cs
When the underlying RabbitMQ client has an unhandled exception it wont get logged anywhere. The `e.ReplyText` will only contain "Unexpected Exception".
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/08d441764a5b676a40e715ea97999915f536da0d/projects/RabbitMQ.Client/client/impl/Connection.Receive.cs#L61-L64
> Log the exception causing the connection shutdown

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.IntegrationTests/Advanced/When_delete_a_queue_with_name.cs
- Source/EasyNetQ.Tests/ExchangeQueueBindingTests.cs
- Source/EasyNetQ/AdvancedBusExtensions.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
It's add a simplified way to delete a queue using only its name. I actually need it in the eventuality I have not the actual 'exact' configuration of the queue (AutoDelete / SAC etc...) to declare it correctly before deletion.
> Add possibility to delete a queue by name on AdvancedBus

- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_is_started_on_exclusive_queue_and_connection_is_dropped.cs
- Source/EasyNetQ/Consumer/Consumer.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
After a connection recovery, a model is recovered, but no consumer could be started if all queues are exclusive, so it could lead to resources leakage.
PR disposes Consumer(and the model) if this sutiation happens.
> Dispose if a consumer contains only exclusive queues

- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_is_cancelled_via_soft_error.cs
- Source/EasyNetQ/Consumer/Consumer.cs
- Source/EasyNetQ/Consumer/InternalConsumer.cs
#1326
1. Stop sending cancelled event if a consumer has been cancelled due to a soft error.
2. Recreate a model if it is closed due to a soft error.
> Recreate a model if it is closed due to a soft error

- Source/Directory.Build.props
- Source/EasyNetQ.ApprovalTests/EasyNetQ.ApprovalTests.csproj
- Source/EasyNetQ.DI.Autofac/EasyNetQ.DI.Autofac.csproj
- Source/EasyNetQ.DI.LightInject/EasyNetQ.DI.LightInject.csproj
- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
- Source/EasyNetQ.DI.Ninject/EasyNetQ.DI.Ninject.csproj
- Source/EasyNetQ.DI.SimpleInjector/EasyNetQ.DI.SimpleInjector.csproj
- Source/EasyNetQ.DI.StructureMap/EasyNetQ.DI.StructureMap.csproj
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
- Source/EasyNetQ.Hosepipe.Tests/EasyNetQ.Hosepipe.Tests.csproj
- Source/EasyNetQ.Hosepipe/EasyNetQ.Hosepipe.csproj
- Source/EasyNetQ.IntegrationTests/EasyNetQ.IntegrationTests.csproj
- Source/EasyNetQ.IntegrationTests/Rpc/When_request_and_respond_inflight_during_shutdown.cs
- Source/EasyNetQ.Logging.Microsoft/EasyNetQ.Logging.Microsoft.csproj
- Source/EasyNetQ.Logging.Serilog/EasyNetQ.Logging.Serilog.csproj
- Source/EasyNetQ.Serialization.NewtonsoftJson/EasyNetQ.Serialization.NewtonsoftJson.csproj
- Source/EasyNetQ.Serialization.Tests/EasyNetQ.Serialization.Tests.csproj
- Source/EasyNetQ.Tests/EasyNetQ.Tests.csproj
- Source/EasyNetQ.Tests/Logging/MessageFormatterTests.cs
- Source/EasyNetQ.sln
- Source/EasyNetQ/EasyNetQ.csproj
- Source/EasyNetQ/Logging/MessageFormatters.cs
- Source/EasyNetQ/PullingConsumerExtensions.cs
- Source/Tests.props
To avoid:
1. Errors connected to multi referencing same package
2. Referencing a package when it is not needed
> Move references from props to csproj

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/Consumer/SimpleConsumerErrorStrategy.cs
It should nack with requeue not to lose messages in a case of cancellation.
PS I'm just trying to implement the following example:
```
using EasyNetQ.Consumer;
using EasyNetQ.Topology;
using EasyNetQ.DI;
// https://www.rabbitmq.com/quorum-queues.html#dead-lettering
var completionTcs = new TaskCompletionSource<bool>();
Console.CancelKeyPress += (_, _) => completionTcs.TrySetResult(true);
using var bus = RabbitHutch.CreateBus(
"host=localhost",
x => x.EnableConsoleLogger()
.EnableNewtonsoftJson()
.Register<IConsumerErrorStrategy>(SimpleConsumerErrorStrategy.NackWithoutRequeue)
);
await bus.Advanced.QueueDeclareAsync(
"Events:Failed",
c => c.WithQueueType(QueueType.Quorum)
.WithDeadLetterExchange(Exchange.Default)
.WithDeadLetterRoutingKey("Events") …
```
> A simple consumer error strategy

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/DeadLetterStrategy.cs
- Source/EasyNetQ/OverflowType.cs
- Source/EasyNetQ/QueueDeclareConfigurationExtensions.cs
https://www.rabbitmq.com/quorum-queues.html#dead-lettering
PS I'm just trying to implement the following example:
```
using EasyNetQ.Consumer;
using EasyNetQ.Topology;
using EasyNetQ.DI;
// https://www.rabbitmq.com/quorum-queues.html#dead-lettering
var completionTcs = new TaskCompletionSource<bool>();
Console.CancelKeyPress += (_, _) => completionTcs.TrySetResult(true);
using var bus = RabbitHutch.CreateBus(
"host=localhost",
x => x.EnableConsoleLogger()
.EnableNewtonsoftJson()
.Register<IConsumerErrorStrategy>(SimpleConsumerErrorStrategy.NackWithoutRequeue)
);
await bus.Advanced.QueueDeclareAsync(
"Events:Failed",
c => c.WithQueueType(QueueType.Quorum)
.WithDeadLetterExchange(Exchange.Default)
.WithDeadLetterRoutingKey("Events")
.WithMessageTtl(TimeSpan.FromSeconds(5)) …
```
> Support of dead-letter-strategy

- Source/EasyNetQ.Logging.Microsoft/ServiceRegisterExtensions.cs
- Source/EasyNetQ.Logging.Serilog/ServiceRegisterExtensions.cs
- Source/EasyNetQ/ServiceRegisterExtensions.cs
In very simple app it doesn't work.
```
var builder = WebApplication.CreateBuilder(args);
builder.Logging.AddSimpleConsole();
builder.Services.RegisterEasyNetQ("host=localhost", c => c.EnableMicrosoftLogging());
var app = builder.Build();
app.MapGet("/", () => "Hello World!");
app.Run();
```
```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: EasyNetQ.Logging.ILogger Lifetime: Singleton ImplementationType: EasyNetQ.Logging.Microsoft.MicrosoftLoggerAdapter': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'EasyNetQ.Logging.Microsoft.MicrosoftLoggerAdapter'.)
---> System.InvalidOperationException: Error while …
```
> Register only generic loggers

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/QueueDeclareConfigurationExtensions.cs
- Source/EasyNetQ/QueueMasterLocator.cs
We don't have a Type suffix nowhere in the codebase.
> Rename QueueMasterLocatorType to QueueMasterLocator

- Source/EasyNetQ/Consumer/AsyncBasicConsumer.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
- Source/EasyNetQ/ServiceRegisterExtensions.cs
There is a closure allocation for every consumed message. It could be easily removed.
Measurements were taken by [Dynamic Program Analysis](https://www.jetbrains.com/help/rider/2022.1/Dynamic_Program_Analysis.html).
Before:
After:
> Rearrange code to eliminate the closure when consuming

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Hosepipe.Tests/Helper.cs
- Source/EasyNetQ.Tests/Internals/AsyncLockTests.cs
- Source/EasyNetQ/Internals/AsyncLock.cs
Based on #1419 . AsyncLock and Releaser are readonly structs now.
> Async lock acquire optimization

- Source/EasyNetQ/Consumer/InternalConsumer.cs
- Source/EasyNetQ/Consumer/NoopDefaultConsumer.cs
Fixes #1466
After a deep investigation of the issue, two things happening in parallel cause it:
1. BasicCancel/BasicCancelNoWait is called to "unsubscribe" a consumer from the queue.
2. There are a lot of messages in the queue and they are arriving because of large prefetch count.
This sample reproduces the issue from the first iteration in my environment.
```
using EasyNetQ.Topology;
var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, _) => cts.Cancel();
using var bus = RabbitHutch.CreateBus(
"host=localhost;publisherConfirms=True",
x => x.EnableNewtonsoftJson()
.EnableAlwaysNackWithoutRequeueConsumerErrorStrategy()
.EnableConsoleLogger()
);
var eventQueue = await bus.Advanced.QueueDeclareAsync(
"Events",
c => c.WithQueueType(QueueType.Quorum) …
```
> Register noop default consumer to prevent disconnection

- Source/EasyNetQ/Consumer/InternalConsumer.cs
- Source/EasyNetQ/Consumer/NoopDefaultConsumer.cs
`NoopDefaultConsumer` shares no state.
Review of #1468
> NoopDefaultConsumer singleton

- Source/EasyNetQ/EasyNetQ.csproj
Because of `IAsyncDisposable` support added in v6.6.0, `Microsoft.Bcl.AsyncInterfaces` is required to compile.
https://github.com/seesharper/LightInject/commit/373ccceaf1f80148388e5e285332236061aba8a4#diff-4ab818dce2e04c8ff0267f39a441efc07c904c8f6167e37fbf0fe0b8aa1abf6eR49
> Bump LightInject to 6.6.0

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/MessageVersioningTests/VersionedExchangeDeclareStrategyTests.cs
- Source/EasyNetQ/AdvancedBusExtensions.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
We have the same for Declare, Delete, Purge, Unbind. Have no idea why it hasn't been done for Bind.
> Allow to bind w/o Exchange/Queue instances

- Source/EasyNetQ.ApprovalTests/ApprovalTests.cs
- Source/EasyNetQ.ApprovalTests/EasyNetQ.ApprovalTests.csproj
- Source/EasyNetQ.ApprovalTests/EasyNetQ.Serialization.SystemTextJson.approved.txt
- Source/EasyNetQ.Serialization.SystemTextJson/EasyNetQ.Serialization.SystemTextJson.csproj
- Source/EasyNetQ.Serialization.SystemTextJson/ServiceRegisterExtensions.cs
- Source/EasyNetQ.Serialization.SystemTextJson/SystemObjectNewtonsoftCompatibleConverter.cs
- Source/EasyNetQ.Serialization.SystemTextJson/SystemTextJsonSerializer.cs
- Source/EasyNetQ.Serialization.Tests/EasyNetQ.Serialization.Tests.csproj
- Source/EasyNetQ.Serialization.Tests/SerializerTests.cs
- Source/EasyNetQ.Serialization.Tests/ServiceRegisterExtensionsTests.cs
- Source/EasyNetQ.sln
Just a draft. 
Two kind of tests are failed:
1. First one, tries to use polymorphic serialize/desealize to non-root properties
2. Second one, does IDictionary<string, object> serialization as part of IBasicProperties which is used in DefaultConsumerErrorStrategy.
> Support SystemTextJson as serializer

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ.Tests/Mocking/MockBuilder.cs
- Source/EasyNetQ/IAdvancedBus.cs
Consider removing `Container` and `Conventions` properties from `IAdvancedBus`.
It seems they are only used in the tests when mocking a custom bus. For me, it's a good sign that there aren't any classes depending on that.
We are using only a subset of EasyNetQ interfaces with an external container.
For example we don't use `IBus`. In that case we don't even have to register unused interfaces in the container.
`IConventions` is the only interface that we have to register, because `IAdvancedBus` depends on that, even though it's not used.
1. `Conventions` shouldn't be in the AdvancedBus anyway. We can add them to `IBus` which contains `IPubSub`, `IRpc` and other communication models that are actually dependent on the conventions.
Still, since the conventions are only configured at container …
> Remove leaked abstractions from IAdvancedBus

- Source/EasyNetQ/Consumer/InternalConsumer.cs
Fixes switched consumer tag and queue name arguments in `InternalConsumer` logger.
> Fix switched logger arguments

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_multi_channel.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_single_channel.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_using_multi_channel.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_using_single_channel.cs
- Source/EasyNetQ.Tests/ConsumeTests/ConsumerTestBase.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_nack_received_from_the_message_handler.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_an_error_occurs_in_the_message_handler.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_cancellation_of_message_handler_occurs.cs
- Source/EasyNetQ/ChannelDispatcher/IPersistentChannelDispatcher.cs
- Source/EasyNetQ/ChannelDispatcher/MultiPersistentChannelDispatcher.cs
- Source/EasyNetQ/ChannelDispatcher/SinglePersistentChannelDispatcher.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/HandlerRunner.cs
- Source/EasyNetQ/Consumer/IConsumerErrorStrategy.cs
- Source/EasyNetQ/Consumer/SimpleConsumerErrorStrategy.cs
- Source/EasyNetQ/DefaultRpc.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/IRpc.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
Inspired by #1518. The idea is that you should not always declare `IDisposable` on interfaces. It's an implementation detail. For example, when you desing your framework to work within DI container - DI container tracks created objects; or you just call `Dispose` on the class variable instead of interface variable. Look - only tests use `Dispose` calls and can be easily changed to use class variable. @Pliner I see other interfaces implementing `IDisposable` but I'm not sure that removing `IDisposable` from interface declaraions is a good idea for all of them. You know better.
> Remove IDisposable from some interfaces

- Source/EasyNetQ/RabbitAdvancedBus.cs
Fixes logger messages for ExchangeBindAsync and ExchangeUnbindAsync.
```
// current log for ExchangeBindAsync ()
[23:33:28 DBG] Unbound destination exchange E2 from source exchange E1 with routing key XYZ and arguments arg1=val1, arg2=val2
// current log for ExchangeUnbindAsync()
[23:33:28 DBG] Unbound destination exchange E2 from source exchange E1 with routing key XYZ and arguments System.Collections.Generic.Dictionary`2[System.String,System.Object]
```
> Fix exchange binding logger

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/AdvancedBusEventHandlersTests.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
Continuation of #1518.
While I removed `Container` and `Conventions` from the interface I actually didn't remove them from the implementation.
> Remove unused properties from RabbitAdvancedBus

- Source/EasyNetQ.Hosepipe/ArgParser.cs
- Source/EasyNetQ.Hosepipe/HosepipeConnection.cs
- Source/EasyNetQ.Hosepipe/Program.cs
- Source/EasyNetQ.Hosepipe/QueueParameters.cs
- Source/EasyNetQ.Hosepipe/Usage.txt
We do use this tool from time to time and some time ago we updated our RabbitMq cluster and discovered that this capability was missing. Pretty straight forward. No Tests for this as the code for the connection is quite cumbersome to test.
> Basic support for ssl/tls connection in Hosepipe

- Source/EasyNetQ/Internals/ReadOnlyMemoryStream.cs
Hi guys
I wanted to use ReadOnlyMemoryStream in my own implementation of serialization, but it turned out that it doesn't work with Newtonsoft.Json.Bson.BsonDataReader (exception in screenshot). It was strange, because if I copy content stream of that type to ordinary MemoryStream the problem doesn't occurs. Because of that I decided to check implementation of that class and I was surprised that count argument is not used in Read function anywhere except validation. I changed all occurrences of buffer.Length to count and thanks to that I resolved my problem. To be honest I'm not an expert in streams, but that implementation looks much more reasonably for me, and most importantly it works :)
> ReadOnlyMemoryStream - Read() doesnt respect count argument - fix

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/When_using_default_consumer_error_strategy.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Conventions.cs
To add the routing key parameter for the error exchange and error queue when default conventions are overriden
> Customise error exchange to error queue binding

- Source/EasyNetQ.ApprovalTests/EasyNetQ.Serialization.SystemTextJson.approved.txt
- Source/EasyNetQ.Serialization.SystemTextJson/JsonHeaderExtensions.cs
- Source/EasyNetQ.Serialization.SystemTextJson/JsonHeaderType.cs
- Source/EasyNetQ.Serialization.SystemTextJson/JsonSerializerOptionsExtensions.cs
- Source/EasyNetQ.Serialization.SystemTextJson/MessagePropertiesConverter.cs
- Source/EasyNetQ.Serialization.SystemTextJson/ServiceRegisterExtensions.cs
- Source/EasyNetQ.Serialization.SystemTextJson/SystemTextJsonSerializerV2.cs
- Source/EasyNetQ.Serialization.Tests/SerializerTests.cs
- Source/EasyNetQ/MessageProperties.cs
Related to #1532.
1. Amqp headers could contain only a fixed list of type.
2. At the moment, serializer are not able deserialize all of them properly, because they serialized as Dictionary<str, object> without custom converters.
The idea here is to save type information for all headers to deserialize them properly.
> Save headers with type info for System.Text.Json

- Source/EasyNetQ.Tests/ConsumeTests/ConsumerTestBase.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_message_is_received.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_polymorphic_message_is_delivered_to_the_consumer.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ.Tests/Interception/BuildInInterceptorsTests.cs
- Source/EasyNetQ.Tests/Mocking/MockBuilder.cs
- Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent.cs
- Source/EasyNetQ.Tests/ProducerTests/When_a_request_is_sent_but_an_exception_is_thrown_by_responder.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
It simplifies tests slightly, because there is no more need to set up AutoResetEvent/CountdownEvent in some cases.
> Await async consumer methods in tests

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
- Source/EasyNetQ.Hosepipe.Tests/MessageReaderTests.cs
- Source/EasyNetQ.Hosepipe/HosepipeMessage.cs
- Source/EasyNetQ.Hosepipe/Program.cs
- Source/EasyNetQ.Tests/ConsumeTests/HandlerCollectionTests.cs
- Source/EasyNetQ.Tests/ConventionsTests.cs
- Source/EasyNetQ.Tests/HandlerRunnerTests/When_a_user_handler_is_executed.cs
- Source/EasyNetQ/ConsumedMessage.cs
- Source/EasyNetQ/Consumer/AsyncBasicConsumer.cs
- Source/EasyNetQ/Consumer/ConsumerExecutionContext.cs
- Source/EasyNetQ/Consumer/DefaultConsumerErrorStrategy.cs
- Source/EasyNetQ/Events/AckEvent.cs
- Source/EasyNetQ/Events/DeliveredMessageEvent.cs
- Source/EasyNetQ/Events/PublishedMessageEvent.cs
- Source/EasyNetQ/Events/ReturnedMessageEvent.cs
- Source/EasyNetQ/MessageReceivedInfo.cs
- Source/EasyNetQ/MessageReturnedEventArgs.cs
- Source/EasyNetQ/ProducedMessage.cs
- Source/EasyNetQ/PullingConsumer.cs
Continues #1586
```
var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, _) => cts.Cancel();
using var bus = RabbitHutch.CreateBus(
"host=localhost", x => x.EnableNewtonsoftJson().EnableAlwaysNackWithoutRequeueConsumerErrorStrategy()
);
var eventQueue = await bus.Advanced.QueueDeclareAsync(
"events",
c => c.WithQueueType(QueueType.Quorum)
.WithOverflowType(OverflowType.RejectPublish),
cts.Token
);
//for (var i = 0; i < 10_000_000; ++i)
//    await bus.Advanced.PublishAsync(Exchange.Default, "events", false, new MessageProperties(), ReadOnlyMemory<byte>.Empty, CancellationToken.None);
using var eventsConsumer1 = bus.Advanced.Consume(eventQueue, (_, _, _) => { });
using var eventsConsumer2 = bus.Advanced.Consume(eventQueue, (_, _, _) => { });
using var …
```
> Convert MessageReceivedInfo to readonly record struct

- Source/EasyNetQ.Tests/Internals/NumberHelpersTests.cs
- Source/EasyNetQ/Internals/NumberHelpers.cs
- Source/EasyNetQ/MessageProperties.cs
- Source/EasyNetQ/MessagePropertiesExtensions.cs
```
using System.Text;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using ConsoleApp1;
BenchmarkRunner.Run<Benchmark>();
[MemoryDiagnoser(false)]
public class Benchmark
{
[Benchmark]
public ulong First()
{
ulong total = 0;
for (var i = 0; i < 10 * 100 * 100 * 100; ++i)
{
var bytes = Encoding.UTF8.GetBytes(i.ToString());
var valueBack = ulong.Parse(Encoding.UTF8.GetString(bytes));
total += (ulong)(valueBack % 2 == 0 ? 1 : 0);
}
return total;
} 
[Benchmark]
public ulong Second()
{
Span<char> charSpan = stackalloc char[20]; // length of ulong.MaxValue
Span<byte> bytesSpan = stackalloc byte[20];
ulong total = 0;
for (var i = 0; i < 10 * 100 * 100 * 100; ++i)
{
var ok = i.TryFormat(charSpan, out var charsWritten);
if (!ok)
throw new InvalidOperationException("TryFormat …
```
> Reduce confirmation id allocations

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/MessagePropertiesTests.cs
- Source/EasyNetQ/AdvancedBusExtensions.cs
- Source/EasyNetQ/DeadLetterExchangeAndMessageTtlScheduler.cs
- Source/EasyNetQ/DefaultPubSub.cs
- Source/EasyNetQ/DefaultRpc.cs
- Source/EasyNetQ/DefaultSendReceive.cs
- Source/EasyNetQ/DelayedExchangeScheduler.cs
- Source/EasyNetQ/Events/PublishedMessageEvent.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
- Source/EasyNetQ/Topology/Exchange.cs
There is no need to pass exchange struct here. It is in line with previous changed made for the topology manipulation methods.
> IAdvancedBus.Publish should accept string as exchange

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/AdvancedBusExtensions.cs
- Source/EasyNetQ/IAdvancedBus.cs
- Source/EasyNetQ/RabbitAdvancedBus.cs
The method body is the same as for:
```
Task PublishAsync(
string exchange,
string routingKey,
bool mandatory,
IMessage message,
CancellationToken cancellationToken = default
);
```
Also, `IMessage<T>` implements `IMessage`, so no changes are needed after removal.
I don`t see any advantages of having it.
> Remove useless generic IAdvancedBus.Publish overload

- Source/EasyNetQ/ConnectionConfigurationExtensions.cs
Original title: If ClientProvidedName is null use connection_name
Starting with EasyNetQ 7.0.0-beta6 the connection_name of a connection is undefined in the RabbitMQ Management UI.
Same bug reported in the past #986. Fixed in #1062. Commit a106dd779674a586362579313fafc3608c59432c broke it (Removal of the line `configuration.Name ??= applicationName;`).
RabbitMQ overrides client property "connection_name". https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/fc08f5a556e96f47198a7376e7ea4ff56d0730a1/projects/RabbitMQ.Client/client/impl/Connection.cs#L1122-L1126
> Set a default ConnectionConfiguration.Name

- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ/DefaultPubSub.cs
This was firstly introduced in 93a67a5a3fc9b4dcd4f5e98d2939ef7afc3196aa.
> Exclusive should be applied only to the consumer

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/DefaultRpc.cs
- Source/EasyNetQ/DefaultTypeNameSerializer.cs
- Source/EasyNetQ/MessageVersioning/VersionedExchangeDeclareStrategy.cs
- Source/EasyNetQ/MultipleExchange/MultipleExchangeDeclareStrategy.cs
- Source/EasyNetQ/Producer/DefaultExchangeDeclareStrategy.cs
These structs were boxed due to lack of IEquatable implementation. Their conversion to records is one of the way to eliminate the boxing.
Before:
After:
> Convert used as a dictionary key structs to record structs

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_multi_channel.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_single_channel.cs
- Source/EasyNetQ/ChannelDispatcher/IPersistentChannelDispatcher.cs
- Source/EasyNetQ/ChannelDispatcher/MultiPersistentChannelDispatcher.cs
- Source/EasyNetQ/ChannelDispatcher/PersistentChannelDispatcherExtensions.cs
- Source/EasyNetQ/ChannelDispatcher/SinglePersistentChannelDispatcher.cs
- Source/EasyNetQ/Internals/AsyncLock.cs
- Source/EasyNetQ/Persistent/IPersistentChannel.cs
- Source/EasyNetQ/Persistent/PersistentChannel.cs
- Source/EasyNetQ/Persistent/PersistentChannelExtensions.cs
The goal of this PR is aimed to optimise the most frequent path for low concurrent execution scenarios in PersistentChannel: 
1. To execute w/o CancellationTokenSource, because there is nothing to cancel.
2. Switch to ValueTask from Task and avoid state machine allocations.
Downside of this approach is double invocations of `Semaphore.Wait`/`Semaphore.WaitAsync`, but it should be not so bad.
Simple low concurrency tests show small speedup(~5 percentages) and a reduction of memory allocations. Before conversion of this draft to PR, I am going to prepare all necessary benchmarks.
> PersistentChannel.InvokeChannelActionAsync fast path optimizations

- Source/EasyNetQ/ResponderConfiguration.cs
Fixes #1661 - ResponderConfiguration.WithMaxPriority() has no effect
> Fix that ResponderConfiguration.WithMaxPriority is not applied to a queue

- Source/EasyNetQ.Tests/ConnectionString/ConnectionStringParserTests.cs
- Source/EasyNetQ/ConnectionString/AmqpConnectionStringParser.cs
- Source/EasyNetQ/ConnectionString/ConnectionStringGrammar.cs
- Source/EasyNetQ/Persistent/PersistentConnection.cs
Alternative to #1671, supports only `ssl=true` parameter.
There is no need to patch hosts because of that:
> Allow to configure ssl in vanilla connection string

- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.DI.Windsor/EasyNetQ.DI.Windsor.csproj
Fixes #1700
See also: https://github.com/EasyNetQ/EasyNetQ/pull/1701
Bump `Castle.Windsor` dependency to `5.1.1` (not `5.1.0` due to this issue: https://github.com/castleproject/Windsor/pull/569) to make it compatible with more recent versions of the container.
Here we cherry-pick #1701 to 8.x
> Make Castle Windsor integration compatible with Castle.Windsor >= 5.1

- Source/EasyNetQ.DI.Tests/BusCreationTest.cs
- Source/EasyNetQ.DI.Windsor/WindsorAdapter.cs
Fixes #1703
Allow to resolve empty collections, so that if extensibility is not registered - we just have an empty collection of things.
See also #1704
> Allow to resolve empty collections in Castle.Windsor

- Source/EasyNetQ.DI.Tests/BusCreationTest.cs
It was initially made for `Castle.Windsor`
> Expand bus creation tests to the supported containers

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ/DefaultRpc.cs
- Source/EasyNetQ/ResponderConfiguration.cs
Classic mirrored queues are not working that well in high load clusters. It would be nice to have option to create request queues as quorum queues.
> Add ability to specify queue type for RPC-style request queue

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Hosepipe.Tests/ErrorMessageRepublishSpike.cs
- Source/EasyNetQ.Hosepipe.Tests/ErrorRetryTests.cs
- Source/EasyNetQ.Hosepipe/Program.cs
- Source/EasyNetQ.Serialization.Tests/SerializerTests.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_consumer_has_multiple_handlers.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_polymorphic_message_is_delivered_to_the_consumer.cs
- Source/EasyNetQ.Tests/DefaultMessageSerializationStrategyTests.cs
- Source/EasyNetQ.Tests/MessageVersioningTests/VersionedMessageSerializationStrategyTests.cs
- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ/ReflectionBasedNewtonsoftJsonSerializer.cs
- Source/EasyNetQ/ServiceRegisterExtensions.cs
This name reflects what is going on under the hood better. Also, its usage is not expected and [EasyNetQ.Serialization.SystemTextJson](https://www.nuget.org/packages/EasyNetQ.Serialization.SystemTextJson) or [EasyNetQ.Serialization.NewtonsoftJson](https://www.nuget.org/packages/EasyNetQ.Serialization.NewtonsoftJson) should be used instead.
Also, it removes a name collision with System.Text.Json.JsonSerialiser.
> Rename JsonSerialiaser to ReflectionBasedNewtonsoftJsonSerializer

- Source/EasyNetQ.IntegrationTests/Advanced/When_consumer_callback_does_not_respect_ct.cs
- Source/EasyNetQ/Consumer/AsyncBasicConsumer.cs
It might prevent a consumer from a shutdown if a message handler doesn't respect CancellationToken.
I have added a test which demonstrates the issue.
> Remove in-flight message counter

- Source/EasyNetQ.ApprovalTests/EasyNetQ.approved.txt
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ/Consumer/AckStrategies.cs
- Source/EasyNetQ/DefaultRpc.cs
- Source/EasyNetQ/Internals/AsyncCountdownEvent.cs
- Source/EasyNetQ/Persistent/PersistentChannel.cs
It is useless trying to publish an error message back because it will be cancelled.
Continues #1752.
> Cancellation should be respected in RPC responder

- Source/EasyNetQ.Tests/SubscribeTests.cs
- Source/EasyNetQ/DefaultPubSub.cs
- Source/EasyNetQ/SubscriptionConfiguration.cs
Using IPubSub, this extension is the only way to configure the queue with a message ttl.
https://www.rabbitmq.com/ttl.html#per-queue-message-ttl
> Extend ISubscriptionConfiguration to support per queue message ttl

- .github/dependabot.yml
- Source/EasyNetQ.DI.Microsoft/EasyNetQ.DI.Microsoft.csproj
- Source/EasyNetQ.DI.Tests/EasyNetQ.DI.Tests.csproj
- Source/EasyNetQ.Logging.Microsoft/EasyNetQ.Logging.Microsoft.csproj
- Upgrade Microsoft extensions package to `6.0` since `5.0` had been out of support
- Remove unnecessary `Microsoft.Extensions.DependencyInjection` reference
- Remove unused configuration package in dependabot
fixes #1760
> upgrade microsoft extensions package to 6.0

- .editorconfig
- Source/EasyNetQ.DI.Tests/ContainerAdaptersData.cs
- Source/EasyNetQ.DI.Tests/MicrosoftDependencyScopeTests.cs
- Source/EasyNetQ.Hosepipe.Tests/ProgramIntegrationTests.cs
- Source/EasyNetQ.Hosepipe.Tests/QueueRetrievalTests.cs
- Source/EasyNetQ.Serialization.NewtonsoftJson/NewtonsoftJsonSerializer.cs
- Source/EasyNetQ.Serialization.Tests/SerializerTests.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_async.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_async_with_subscription_configuration.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_async_with_subscription_configuration_action.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_async_with_subscription_configuration_action_and_attribute.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_with_explicit_implementation.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_with_subscription_configuration.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_with_subscription_configuration_action.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_with_subscription_configuration_action_and_attribute.cs
- Source/EasyNetQ.Tests/AutoSubscriberTests/When_auto_subscribing_with_subscription_configuration_attribute_no_expires.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_multi_channel.cs
- Source/EasyNetQ.Tests/ChannelDispatcherTests/When_an_action_is_invoked_that_throws_using_single_channel.cs
- Source/EasyNetQ.Tests/ConsumeTests/When_a_responder_is_cancelled.cs
- Source/EasyNetQ.Tests/DefaultMessageConsumerTests.cs
- Source/EasyNetQ.Tests/StubCorrelationIdGenerator.cs
> Enable ca 1852 rule

- Source/EasyNetQ.Serialization.SystemTextJson/EasyNetQ.Serialization.SystemTextJson.csproj
With this change STJ will no longer be included in net 6 due to the framework being able to provide it
Closes #1783
> STJ will now only be included for Net Standard

- Source/Directory.Build.props
This moves the package to be using a license expression rather than including a license file
Closes #1784
> Set license expression rather than a file
